### ISSUE TITLE
Install error: "abort: m??$0??0????%:????:??$"

### ISSUE THREAD

**Issue by ViDtje** [stephen/airsonos#101]
I used to run airsonos on the Raspberry Pi B+, but recently bought the Raspberry Pi 2. After I reinstalled everything again, I tried to install airsonos. But I always get an abort message.
Could it be that it has something to do with the new hardware?

The output is the following:

pi@raspberrypi ~ $ sudo npm install airsonos -g
abort: m??$0??0????%:????:??$

==== Stack trace ============================================

Security context: 0x41c34659 <JS Object>#0#
    1: _emitChunk [/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:~73] (this=0x301ee725 <a BlockStream>#1#,flush=0x41c08091 <undefined>)
    2: arguments adaptor frame: 0->1
    3: resume [/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:~55] (this=0x301ee725 <a BlockStream>#1#)
    4: arguments adaptor frame: 1->0
    5: resume [/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:~251] (this=0x301ee6ad <an Extract>#2#,who=0x41c08091 <undefined>)
    6: arguments adaptor frame: 0->1
    7: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:257] (this=0x407e5c59 <an Entry>#3#)
    8: emit [events.js:~53] (this=0x407e5c59 <an Entry>#3#,type=0x58816529 <String[6]: resume>)
    9: resume [/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry.js:~90] (this=0x407e5c59 <an Entry>#3#)
   10: ondrain [stream.js:61] (this=0x407cafc1 <a FileWriter>#4#)
   11: emit [events.js:~53] (this=0x407cafc1 <a FileWriter>#4#,type=0x20229861 <String[5]: drain>)
   12: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/fstream/lib/file-writer.js:50] (this=0x407c84f1 <a WriteStream>#5#)
   13: emit [events.js:~53] (this=0x407c84f1 <a WriteStream>#5#,type=0x20229861 <String[5]: drain>)
   14: afterWrite [_stream_writable.js:~275] (this=0x41c34701 <JS Global Object>#6#,stream=0x407c84f1 <a WriteStream>#5#,state=0x407dfff9 <a WritableState>#7#,finished=0x41c080c1 <false>,cb=0x5a1e8245 <JS Function>#8#)
   15: onwrite [_stream_writable.js:~249] (this=0x41c34701 <JS Global Object>#6#,stream=0x407c84f1 <a WriteStream>#5#,er=0x41c08091 <undefined>)
   16: /* anonymous */ [_stream_writable.js:~96] (this=0x41c34701 <JS Global Object>#6#,er=0x41c08091 <undefined>)
   17: arguments adaptor frame: 0->1
   18: /* anonymous */ [evalmachine.<anonymous>:1695] (this=0x41c34701 <JS Global Object>#6#,er=0x41c08081 <null>,bytes=512)
   19: arguments adaptor frame: 3->2
   20: oncomplete(aka wrapper) [evalmachine.<anonymous>:522] (this=0x4a58602d <an Object>#9#,err=0x41c08081 <null>,written=512)

**Comment by JaspalX** [comment]
This looks similar to https://github.com/stephen/airsonos/issues/75 
I have a pi2 (thinking I could use the extra power to ensure good streaming) and had the same crash as you ViDtje. Node v0.10.36 and npm v1.4.28  whereas my build on a pi1 worked fine.

Any hints as to what to look at very welcome!

Strangely, after installing forever (as in issue 75), the build of airsonos seemed to complete, but I now get the same crash as that guy had. I won't post the whole trace, but it starts:
```
sudo airsonos
abort: m??$0??0????%:????:??$

==== Stack trace ============================================

Security context: 0x56634659 <JS Object>#0#
    1: parse [/usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/coffee-script/lib/coffee-script/parser.js:~479] (this=0x56493435 <an Object>#1#,input=0x5b3645b5 <JS Array[678]>#2#)
```

**Comment by ViDtje** [comment]
I fixed it! I installed Node.js version 0.10.28 by compiling it on the Raspberry Pi itself. I used this walkthrough: http://www.armhf.com/node-js-for-the-beaglebone-black/ . You just need to make sure you install version 0.10.28. After that, I installed Airsonos, now everything works perfectly!

**Comment by JaspalX** [comment]
Awesome, thanks, that really helped me and fixed it for me too. I had to run 
````
sudo apt-get install libavahi-compat-libdnssd-dev libasound2-dev
npm install airsonos -g
````
to get my install to work but it did.

**Comment by codebender** [comment]
@ViDtje @stephen I followed those instructions (http://www.armhf.com/node-js-for-the-beaglebone-black/) but replaced 0.10.28 with 0.10.33 and it worked for me
