### ISSUE TITLE
Airsonos install issue on Mac OS 10.7 

### ISSUE THREAD

**Issue by Nesanime** [stephen/airsonos#102]
Hi Stephen, 
I am trying to install Airsonos , but I can't get trough...

OSX 10.7.4
After some hours I've got these installed and working..

Homebrew 0.9.5
Node v0.12.0
npm 2.5.1

but when I am trying to run Airsonos i get this error:

```
20 errors generated.
make: *** [Release/obj.target/bindings/src/node_lame.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 11.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 11.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! lame@1.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame

```

I've been looking to other threads as this one https://github.com/stephen/airsonos/issues/58
but no success...

Any idea what I am doing wrong?

Thanks a lot!!!!

**Comment by girvo** [comment]
I have the same problem on a clean OS X 10.10 -- `node-gyp rebuild` is choking and dying :(

**Comment by derbbre** [comment]
Same problem, OS X 10.9.5, homebrew node install. Looks like a problem with node-lame, really, not airsonos. Same errors occur with 'npm install lame'.

Build output and npm-debug.log on gist:
https://gist.github.com/derbbre/8930a8693ad111dc75e4

**Comment by stephen** [comment]
Currently don't support node version `0.12.x`. See: https://github.com/stephen/airsonos/issues/33 for a workaround, using `0.10.x`
