### ISSUE TITLE
an install issue

### ISSUE THREAD

**Issue by stustaff** [stephen/airsonos#104]
I have taken a look belo but cant seem to see thsi issue

this is the output im getting when i try to install same via npm too.

macmini:airsonos myname$ npm install -g
npm WARN locking Error: EACCES, open '/Users/myname/.npm/_locks/airsonos-bf1f7f73d8dceb14.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/myname/.npm/_locks/airsonos-bf1f7f73d8dceb14.lock failed { [Error: EACCES, open '/Users/myname/.npm/_locks/airsonos-bf1f7f73d8dceb14.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/myname/.npm/_locks/airsonos-bf1f7f73d8dceb14.lock' }
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/myname/.node/lib/node_modules/airsonos, which hasn't been locked

thanks

**Comment by stephen** [comment]
Should use `sudo npm cache clean` then `sudo npm install -g airsonos`
