### ISSUE TITLE
Install Question - OS X 10.10.2

### ISSUE THREAD

**Issue by studio449** [stephen/airsonos#108]
Hi Stephen,
still have some trouble installing airsonos. I tried node 0.10.x, as you suggested, but still no success.
Please help!

Here's the terminal log:

Stefans-iMac:airsonos stefanburner$ sudo npm install -g
Password:
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/nodetunes/0.1.2
npm http GET https://registry.npmjs.org/portastic/0.0.1
npm http GET https://registry.npmjs.org/nicercast/0.0.8
npm http GET https://registry.npmjs.org/sonos/0.6.1
npm http GET https://registry.npmjs.org/ip/0.3.2
npm http GET https://registry.npmjs.org/flags
npm http GET https://registry.npmjs.org/throttle
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/portastic/0.0.1
npm http 304 https://registry.npmjs.org/nicercast/0.0.8
npm http 304 https://registry.npmjs.org/sonos/0.6.1
npm http 304 https://registry.npmjs.org/flags
npm http 304 https://registry.npmjs.org/nodetunes/0.1.2
npm http 304 https://registry.npmjs.org/ip/0.3.2
npm http 304 https://registry.npmjs.org/throttle
npm http GET https://registry.npmjs.org/lame
npm http GET https://registry.npmjs.org/icecast-stack
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/stream-parser
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/forge
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/mdns/2.2.2
npm http GET https://registry.npmjs.org/metricstream/0.0.0
npm http GET https://registry.npmjs.org/httplike/1.0.1
npm http GET https://registry.npmjs.org/priorityqueuejs/0.2.0
npm http GET https://registry.npmjs.org/random-mac/0.0.4
npm http GET https://registry.npmjs.org/node-forge
npm http GET https://registry.npmjs.org/randomstring/1.0.3
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/upnp-client/0.0.1
npm http GET https://registry.npmjs.org/xml2js
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/debug
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/commander'
File exists: /usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/commander
Move it away, and try again. 

npm ERR! System Darwin 14.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/stefanburner/airsonos
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/commander
npm ERR! fstream_path /usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/commander/History.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/coffee-script/bin'
npm ERR! error rolling back  airsonos@0.0.26 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/coffee-script/bin']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/coffee-script/bin' }
npm ERR! Error: No compatible version found: debug@'^2.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/stefanburner/airsonos
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/async/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/stefanburner/airsonos
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/async/README.md
npm ERR! fstream_path /usr/local/lib/node_modules/airsonos/node_modules/portastic/node_modules/async/README.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/forge
npm http 304 https://registry.npmjs.org/mdns/2.2.2
npm http 304 https://registry.npmjs.org/lame
npm http 304 https://registry.npmjs.org/httplike/1.0.1
npm http 304 https://registry.npmjs.org/icecast-stack
npm http 304 https://registry.npmjs.org/stream-parser
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/node-forge
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/metricstream/0.0.0
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/xml2js
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/upnp-client/0.0.1
npm http 304 https://registry.npmjs.org/string_decoder
npm WARN package.json upnp-client@0.0.1 No repository field.
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/priorityqueuejs/0.2.0
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/step
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/random-mac/0.0.4
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/randomstring/1.0.3
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.3
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/ctype/0.5.3
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/step
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 200 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tgz
npm http 200 https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/stefanburner/airsonos/npm-debug.log
npm ERR! not ok code 0

**Comment by stephen** [comment]
`0.10.12` is 1.5 years old. Try the latest version, v0.10.36`. I've updated the readme to reflect this.
