### ISSUE TITLE
Install fails on Mac OS X Yosemite 10.10.2

### ISSUE THREAD

**Issue by mdmadhu** [stephen/airsonos#116]
Not very sure what's going on here, but thought someone might be able to guide me to get this working.
Thanks!

===
> mdns@2.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
 
> lame@1.1.2 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! lame@1.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

**Comment by cristianojeda** [comment]
I'm also going through the same problem

**Comment by paulyscott** [comment]
Hi... I have the exact same errors.... Any pointers Stephen ?

**Comment by stephen** [comment]
You should use `sudo` when installing globally.

**Comment by paulyscott** [comment]
Hi Stephen....
Sudo was used to elevate the terminal session using sudo -s followed by the standard call for installation "npm install airsonos -g" also tried running "sudo npm install -g --unsafe-perm airsonos" from a standard terminal session... both give the same result

**Comment by cristianojeda** [comment]
$ sudo npm install -g cordova ionic

npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine cordova-js@3.7.3: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
\

**Comment by eristoddle** [comment]
I am having the same issue with node v0.12.2 and v2.9.1. Makes my project dead in the water and am switching to my ubuntu laptop to hope it works there.
