### ISSUE TITLE
Automatic Start Airsonos

### ISSUE THREAD

**Issue by grisu0816** [stephen/airsonos#137]
Is it possible to start airsonos automatically on the pi start ? I don't now how !

**Comment by wboerhout** [comment]
put the following line in /etc/rc.local:

sudo -u root -i /path/to/airsonos

(lookup the correct path for airsonos with "whereis airsonos" or "which airsonos")

the -i makes sure that the process created for airsonos has the same environment setup as an interactive login, so all PATH info is correct.

**Comment by stephen** [comment]
This isn't in the current scope of the project. Another solution: https://github.com/stephen/airsonos/issues/197

**Comment by rafaelsantander** [comment]
to use crontab you need to make sure the node's path is explicitly called 

A. find the location of airsonos script by executing `which airsonos`
B. set the node path explicitly on the first line
i.e. 
emacs /usr/local/bin/airsonos

`#!/usr/bin/env` **/usr/local/bin/node**`

C. create the restart script : 
`emacs /tmp/keepAliveASonos.sh`

copy this script in
`#!/bin/sh
if ps -ef | grep -v grep | grep airsonos ; then
        echo "airsonos is running"
        exit 0
else
        /usr/local/bin/airsonos&
	echo "airsonos restarted"
        exit 0
fi`

D. set the permissions : `chmod 755 /tmp/keepAliveASonos.sh`

E. setup your cron to execute every 5 min by doing the following 

- `crontab -e`
- `*/5 * * * * /tmp/keepAliveASonos.sh > /tmp/asonosRestart.log`
