### ISSUE TITLE
Only via terminal? 

### ISSUE THREAD

**Issue by Larsutrecht** [stephen/airsonos#139]
As a starter (dummie) in Terminal, I finally managed to install (I think?) Airsonos. 

MacBook-Pro-van-Lars:airsonos larslijding$ node index.js
Searching for Sonos devices on network...
Setting up AirSonos for Lars {192.168.178.21:1400}

It works! But..
Does Airsonos only work when u type this in Terminal? 
And it disappears out of the sound output list when closing Terminal. Is there any next step I missed? 
When I play a video, there is a gap of a second in music. How do I solve this?

Thanks!

**Comment by mattijsbliek** [comment]
There's 3 options basically:
1. Run it with nohup so you can safely close the terminal: `nohup airsonos &`
2. Create an Automator process which runs during startup
3. Use the SonoAir wrapper: http://sonoair.mihosoft.eu/
