### ISSUE TITLE
Need ability to adjust volume for grouped rooms together

### ISSUE THREAD

**Issue by williamw** [stephen/airsonos#14]
I use the Sonos controller to group my 3 rooms grouped together so the same music plays in all of them. All 3 Sonos devices appear in the AirPlay list on my iOS devices, so I just select the "master" room (the one I grouped the other 2 rooms into using the Sonos controller app). When I adjust the volume on my iOS device, it only affects the "master" room where I'd expect it to adjust the volume in all 3.

(It could be a tricky problem because the volumes in the different rooms can be set at different levels. I think the way the Sonos controller app handles this is it increases or decreases each room by a relative value, say +5 or -5 db rather than setting each room to the same value.)

**Comment by StephenOTT** [comment]
:+1: having this exact issue
