### ISSUE TITLE
Cannot connect to AirSonos from iTunes/12.1

### ISSUE THREAD

**Issue by rheid** [stephen/airsonos#140]
Hi Stephen,

Airsonos works fine on iOS but if I try to connect from my mac I get a error:

airsonos --verbose
Searching for Sonos devices on network...
Setting up AirSonos for Spielzimmer {192.168.178.55:1400}
  nodetunes:server starting nodetunes server (Spielzimmer (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5001) +9ms
  nodetunes:rtsp received method OPTIONS (CSeq: 1)
{ cseq: '1',
  'user-agent': 'iTunes/12.1 (Macintosh; OS X 10.10.3)',
  'client-instance': 'B9BFAB9ED8E82F83',
  'dacp-id': 'B9BFAB9ED8E82F83',
  'active-remote': '111830835',
  'apple-challenge': 'DYUcPFXZb4W6bFcJl6VE6A' } +25s
  nodetunes:helper building challenge for DYUcPFXZb4W6bFcJl6VE6A== (ip: c0a8b23f, mac: 545200cd26d4) +1ms
  nodetunes:helper computed challenge: R+JLv4JvPvxZ10sDrBUJAIVE7uJZxquiaW/pzxtvRKkFQBBLO215TTI7Y/bDEK7HEHIsnYkMm7I9Sh1os7K++07mmt436p5YsL9Ge+oc3cqLxDRRPoVDC2dJnT4eBGw9GW8MzW1DzNEThh2ph4jdyunVMb7EA/O9w0gbeZgy9xwp/J7lqIhJ3375MEaRsZvKacKFBqZKSdGk/cN9CcaMrp/B6YiCy0EFdUixsoQmvqlFAjdiMxWJOSwxuyhCI8/MD12JZQdY529Jj/+i/u0PPM9rDRY5Ry080zegCb1lKKPXwH8wRAy5aQho7+q6/+cKv4FWUl/a7EA/plgkuorPCQ== +61ms
  nodetunes:rtsp received method OPTIONS (CSeq: 1)
{ cseq: '1',
  'user-agent': 'iTunes/12.1 (Macintosh; OS X 10.10.3)',
  'client-instance': 'B9BFAB9ED8E82F83',
  'dacp-id': 'B9BFAB9ED8E82F83',
  'active-remote': '1838118501',
  'apple-challenge': 'tw7J8BeI4rmhCemKK+XBOw' } +1m
  nodetunes:helper building challenge for tw7J8BeI4rmhCemKK+XBOw== (ip: c0a8b23f, mac: 545200cd26d4) +1ms
  nodetunes:helper computed challenge: f1kXOO4F4kbjbkbPdiFVDnCS1AN1XwM8aAoqVoBvJgbCrKRikSZHW/tk7MgtPDKFcyc410EyK8GRlMgVuuqFF2pd862sFhtJT+4rXjBWFGESPDrP5ygoEDUUJkWXSr/3B9fejoJb1ZR6JQjfur0GuND2T8GfROHwkgHHCEdD82RbaNB/p1vs6K7L4EhBweqDZsJI+W/qNDvrEToA6wv+bmfP3EeIBKlEkWTC0ODpW8WOJNZBS/8D1G3HgjzNc1ZKAHhmxby/2fMoye49Ge2EFlc8Y9sJStf9XJ0ZwuWM5OJOfltOvQHDVvWxhFThliCC7f0MQs/FsewRhZNpj7Ffvw== +54ms

**Comment by nbsoftware** [comment]
Hi Stephen,

I was having this issue with my late tries with airsonos a few months ago and tried again yesterday with the updated 0.1.1 version but I am sorry to report that I'm still having the same error (cannot connect to...) with the very same kind of debug info as above. Maybe worth to be mentioning, airsonos is adding each of my devices twice... don't know if it has anything to do with it. I'd be happy to provide you with some other debug info and run tests for you if you would like to.

Thanks.

airsonos --verbose
Searching for Sonos devices on network...
Setting up AirSonos for Cuisine {192.168.20.135:1400}
  nodetunes:server starting nodetunes server (Cuisine (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +9ms
Setting up AirSonos for Salon {192.168.20.108:1400}
  nodetunes:server starting nodetunes server (Salon (AirSonos)) +1ms
  nodetunes:server broadcasting mdns advertisement (for port 5001) +7ms
Setting up AirSonos for Cuisine {192.168.20.135:1400}
  nodetunes:server starting nodetunes server (Cuisine (AirSonos)) +1ms
  nodetunes:server broadcasting mdns advertisement (for port 5002) +6ms
Setting up AirSonos for Salon {192.168.20.108:1400}
  nodetunes:server starting nodetunes server (Salon (AirSonos)) +2ms
  nodetunes:server broadcasting mdns advertisement (for port 5003) +6ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x7831c1d72636',
  'apple-challenge': 'XWHMXVX3PpDQtP5sZc23wg==',
  'dacp-id': '3A935E2C68914C06',
  'active-remote': '3915907336',
  'user-agent': 'AirPlay/215.18' } +34s
  nodetunes:helper building challenge for XWHMXVX3PpDQtP5sZc23wg== (ip: c0a8140b, mac: 545200b62964) +1ms
  nodetunes:helper computed challenge: uHpUfT7/66emSHr+QxFgBi8u0VFB4UU3KDwQtQ7vHIbabMLL2ntShmPoATvefdplapA0Cn9XraB6SJFEgD2EnClv9FCayetxu9wHvsz7lvWCr7Ty5PGO4AOd7IxgDmfeo5F/wpbb8mfBxrjhvAlO38pOQs76OXYHAf9A80azj7SJFwV6fRP0pLL3XzE/6qaNEMxWBE6mSF1oBMgoZu17Eea+Jvg+Pjea0DnvXmGanLvyxjmhavRZWYtoBTqsTXt+oZuxmC9WCKbDKUIOLIiDPc2cLwZaRRr5C9nILp+tqFLR4qfcyvoXUwMSIFKvu1XeTkhme7LoRbrdUO37d5atBw== +57ms

**Comment by nbsoftware** [comment]
Having read here and there it seems it comes down to nodetunes.
Running 'node /usr/local/lib/node_modules/nodetunes/examples/server_stdout.js' does give me the same error message 'Could not connect to NodeTunes Stdout". Damn. I am a bit stuck from there.

**Comment by stephen** [comment]
Lack of iTunes support is a known issue - see https://github.com/stephen/nodetunes/issues/1

@nbsoftware - Separately, I think your issue might be resolved by ipv6 support - https://github.com/stephen/nodetunes/pull/32
