### ISSUE TITLE
PC: Next Steps after Setting Up AirSonos for room [IP]

### ISSUE THREAD

**Issue by jtrzcin** [stephen/airsonos#142]
On my mac,  I succeeded to set up AirSonos and I see an extra speaker device (AirSonos) in Sound. I can activate the speaker and the sounds of my mac goes on the sonos. superb. 

However, on my pc (Windows 7), I don't see any extra devices for the sound speaker. no sounds from my pc go to the sonos. The last step in the command seems correct:
"Setting Up AirSonos for room#1 [IP]"
"Setting Up AirSonos for room#2 [IP]"

What comes next ? Is it a configuration issue? Should I use another software? 
Thanks

**Comment by stephen** [comment]
I don't think Windows 7 supports AirPlay directly. See: https://support.apple.com/en-us/HT204289
