### ISSUE TITLE
Windows server 2003

### ISSUE THREAD

**Issue by RafikE** [stephen/airsonos#148]
![server 2003](https://cloud.githubusercontent.com/assets/11830320/7018155/1ce3432a-dd01-11e4-9585-c2f3cc6ce8a9.jpg)

Have been using airsonos for a few days on my laptop but its not that 

When I try to start tthe airsonos server I get this message. 

Since a server doesn't have the same locations for the users I have just made the folder directory for the airsonos files. 

It does respond to the where airsonos command with the right directory'. I'm not sure what this message exactly means can someone explain this to me with perhaps a sollution?

Thanks in advance!

**Comment by stephen** [comment]
You need to install the dependencies for airsonos, not just copy the source files. `npm install` should do this in that directory.
