### ISSUE TITLE
OS X 10.10.2 - airsonos 0.1.1 - no system audio 

### ISSUE THREAD

**Issue by pgeschke** [stephen/airsonos#150]
Hey,

I have one Sonos Play 1 which i tried to connect to my Mac Pro's system audio via AirSonos.
After starting Airsonos, i can select it as Audiotarget in settings, but it immediately gets de-selected again.

I have attached the verbose output of airsonos.

Any help would be greatly appreciated.

```
Patricks-Mac-Pro:~ pgeschke$ airsonos --verbose
Searching for Sonos devices on network...
Setting up AirSonos for Büro {10.1.15.84:1400}
  nodetunes:server starting nodetunes server (Büro (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +19ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x17f204e3d6',
  'apple-challenge': 'oBUXRuh3wyhqrvhXazCkHg==',
  'dacp-id': '7F2118670D984128',
  'active-remote': '1307207608',
  'user-agent': 'AirPlay/215.15' } +12s
  nodetunes:helper building challenge for oBUXRuh3wyhqrvhXazCkHg== (ip: 0a010f4b, mac: 545200c0b5c5) +2ms
  nodetunes:helper computed challenge: MedO6cjlMsNRLwOzUlaRvP1q5dvVc4cwVY+VEhhoHgXTQS0vDGCrO4jDlXqu/OnHqSvxbzc8HX6DGl2Cr9O1bCgx/Yi9QgS8xEiSJgQSZvBkCysIQq4i9nrQkj5V/WMUDqnMTNIzSRp++cxQauzgTZkdF6YDQMIpwbaS00fwWngHVnB/2B5UKdmSyg2/u4qQFZDitj7gHAmVhX2mhaaI6mtShcNsa5qTaPCOUElX1XLRBisTd0s5f7cjrF+2YMaZVA7TuML9yzItO54KjZzYgTj4Tx6vpb4iTLQPcVmwNHU1YNwo7yhXD9P9bRt/DIZ8Dx+yOVJ/vhQQWSfQAIPXeA== +105ms
  nodetunes:rtsp received method OPTIONS (CSeq: 1)
{ cseq: '1',
  'x-apple-device-id': '0x17f204e3d6',
  'apple-challenge': '5qvoIYODdv48yaKqKxiZgA==',
  'dacp-id': '7F2118670D984128',
  'active-remote': '3579293683',
  'user-agent': 'AirPlay/215.15' } +4s
  nodetunes:helper building challenge for 5qvoIYODdv48yaKqKxiZgA== (ip: 0a010f4b, mac: 545200c0b5c5) +0ms
  nodetunes:helper computed challenge: 5Kf6WTLZgJ/CL17TGCxkqlYTc4OtCKM2gWA0VHeIX8BfPBOlhXhXjm49vVfiDUKkzY7A76RqHL7SqTX65SNjlYxvMAg38VS6GcTT3M3W5h2/P1UGVtUm9yI1j4mwphryOLm4krcagTx7M/MqttK70mZNkP55SHt5bMoZS+hFppyyorM3vCWgQHPim4DK8KV8qNEDV4KF0CZ5MCXRR+i65gRgHluI4Kqbjdb6y6CYl7QExfpxmTQeyyZpV4W6G1C4a5MWWBkmXHBM+tDFChP/09gIdJyexoaGSf6T805AtxrOu2DfIWxDOCj+ukY1EZMnXouWg/FzalVmLfDzZzsAtA== +75ms
  nodetunes:rtsp received method OPTIONS (CSeq: 2)
{ cseq: '2',
  'x-apple-device-id': '0x17f204e3d6',
  'apple-challenge': 'kedDVuMgNsLbylM5x1FLuQ==',
  'dacp-id': '7F2118670D984128',
  'active-remote': '3540115116',
  'user-agent': 'AirPlay/215.15' } +3s
  nodetunes:helper building challenge for kedDVuMgNsLbylM5x1FLuQ== (ip: 0a010f4b, mac: 545200c0b5c5) +1ms
  nodetunes:helper computed challenge: wAGm5kGV3hkI7u6UhzOx0SydIwXTnKBr52IMC8wt/UAnfnS9639Huq35XA3crEfVzXgqr1eevIkDWF5Z5TjJYKGJuPShD0Bpp03yFSAdPDENJYyfJ4FRoX4FlKaQFeP2v2ehqPtEdPN9NDqTBEJLOa0l/ZeLgmJyKUzlQvaMh5l+vATHHFIKhL0CgLvDVBcJlyu7jYawleQE5GVQD5UlBJt5Yvuk6HiJzW6kEnjMUW7VrcEIJnObh7d9vzMy3Q1gaXyubwVvEEs9mhTG+D4hA44ypEd/v0i2sC3dSRYfcQpsvA1/Im5tKQI2aYH9ylGQKGGsTEmFn5JiRjiLTlynQA== +66ms
  nodetunes:rtsp received method OPTIONS (CSeq: 3)
{ cseq: '3',
  'x-apple-device-id': '0x17f204e3d6',
  'apple-challenge': '7Kzy6zrgBjOqKAAF2LItmg==',
  'dacp-id': '7F2118670D984128',
  'active-remote': '2384812384',
  'user-agent': 'AirPlay/215.15' } +6s
  nodetunes:helper building challenge for 7Kzy6zrgBjOqKAAF2LItmg== (ip: 0a010f4b, mac: 545200c0b5c5) +0ms
  nodetunes:helper computed challenge: tS1H7xgPaF9mVE4B8/esFQEBSfKyjYbb8ye8gvFTnw4orJwynnROBejpdrj7VncFwj3Nn3LLc65eKni8uvK1dcf7V2ZoM3W+FO2zKhKobeo2sp/+hZ4CqCceiOWdikIDnWCIj8+ar6qPM/y11RqVGcG2DMNRVUfVTufy8Tt7QNF/ldrWwOkiIciIBjp3fP9AzZmoskolCDRfIpLexFroil3kV8g8X3O/4Xm/3dntSoru34K3NMqZXrHjQ+C+pZoERX3G/JWBBcEyQxgyGGw8ws+ln7Wc2KLxrLPHeeHgqVdY+2YEndRtHQKXpCOJa2QtTzHNT+BSbYvCVR5/LFPz6A== +64ms
```

**Comment by pgeschke** [comment]
Is there any more info i can deliver to maybe make things a little bit more clear?
I really like the Sonos Speakers and would love to stock up on them, but not if im permanently stuck with the UBERcool SONOS app.

**Comment by Bubba** [comment]
I'm getting the same problem too.

    Searching for Sonos devices on network...
    Found Sonos device: {10.0.1.8:1400} seen before - skipping it
    Found Sonos device: {10.0.1.2:1400} seen before - skipping it
    Found Sonos device: {10.0.1.7:1400} seen before - skipping it
    Found Sonos device: {10.0.1.6:1400} seen before - skipping it
    Setting up AirSonos for Living Room {10.0.1.6:1400}
      nodetunes:server starting nodetunes server (Living Room (AirSonos)) +0ms
      nodetunes:server broadcasting mdns advertisement (for port 5000) +7ms
    Setting up AirSonos for ZoneBridge {10.0.1.2:1400}
      nodetunes:server starting nodetunes server (ZoneBridge (AirSonos)) +4ms
      nodetunes:server broadcasting mdns advertisement (for port 5001) +4ms
    Found Sonos device: {10.0.1.8:1400} seen before - skipping it
    Found Sonos device: {10.0.1.2:1400} seen before - skipping it
    Found Sonos device: {10.0.1.7:1400} seen before - skipping it
    Found Sonos device: {10.0.1.6:1400} seen before - skipping it
    Setting up AirSonos for Office {10.0.1.8:1400}
      nodetunes:server starting nodetunes server (Office (AirSonos)) +28ms
      nodetunes:server broadcasting mdns advertisement (for port 5002) +6ms
     Setting up AirSonos for Family Room {10.0.1.7:1400}
      nodetunes:server starting nodetunes server (Family Room (AirSonos)) +24ms
      nodetunes:server broadcasting mdns advertisement (for port 5003) +4ms

**Comment by stephen** [comment]
Which version of node were you running on? 0.12 was previously not supported but now is after airsonos 0.2.2
