### ISSUE TITLE
Airsonos on OSX 10.9.5 - TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by jfrolick** [stephen/airsonos#151]
Hi.  I'm having an issue when starting Airsonos.  I looked around for similar issues, and the closest thing I could find was an issue regarding the BOOST device (Issue #97).  The diagnostic utility seems to find everything.  Any help would be greatly appreciated.

★XXXXX@grawr:~> airsonos
Searching for Sonos devices on network...
/usr/local/lib/node_modules/airsonos/lib/main.js:30
    devices.forEach(function(device) {
           ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/airsonos/lib/main.js:30:12
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:105:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:129:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:129:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:575:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14

Here is the diagnostics output:

★jfrolick@grawr:~> cat diag
AirSonos Diagnostics
node version	 v0.12.2
operating sys	 darwin (x64)
ip address	 192.168.1.13

Searching for Sonos devices on network...

Device 	{"host":"192.168.1.56","port":1400,"state":{}} (BR200)
`- attrs: 	{"CurrentZoneName":"BOOST",
		"CurrentIcon":"x-rincon-roomicon:viper",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"28.1-83040",
		"DisplaySoftwareVersion":"5.2",
		"HardwareVersion":"1.12.1.2-1",
		"IPAddress":"192.168.1.56",
		"MACAddress":"XX:XX:XX:XX:XX:F8",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E9373F4C5601400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.60:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"8",
		"uuid":"RINCON_B8E9373F4C5601400",
		"name":"Living Room"},{"group":"RINCON_B8E9373D977201400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.59:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"6",
		"uuid":"RINCON_B8E9373D977201400",
		"name":"Living Room"},{"group":"RINCON_B8E93761513001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.58:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"4",
		"uuid":"RINCON_B8E93761513001400",
		"name":"Living Room"},{"group":"RINCON_B8E9377A0F5201400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.57:1400/xml/device_description.xml",
		"version":"28.1-83251",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9377A0F5201400",
		"name":"Living Room"},{"group":"RINCON_B8E9370263F801400:0",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.56:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9370263F801400",
		"name":"BOOST"}]

Device 	{"host":"192.168.1.58","port":1400,"state":{}} (ANVIL)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"28.1-83040",
		"DisplaySoftwareVersion":"5.2",
		"HardwareVersion":"1.8.2.4-1",
		"IPAddress":"192.168.1.58",
		"MACAddress":"XX:XX:XX:XX:XX:30",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E9373F4C5601400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.60:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"8",
		"uuid":"RINCON_B8E9373F4C5601400",
		"name":"Living Room"},{"group":"RINCON_B8E9373D977201400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.59:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"6",
		"uuid":"RINCON_B8E9373D977201400",
		"name":"Living Room"},{"group":"RINCON_B8E9370263F801400:0",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.56:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9370263F801400",
		"name":"BOOST"},{"group":"RINCON_B8E9377A0F5201400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.57:1400/xml/device_description.xml",
		"version":"28.1-83251",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9377A0F5201400",
		"name":"Living Room"},{"group":"RINCON_B8E93761513001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.58:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"4",
		"uuid":"RINCON_B8E93761513001400",
		"name":"Living Room"}]

Device 	{"host":"192.168.1.57","port":1400,"state":{}} (ZPS9)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"28.1-83251",
		"DisplaySoftwareVersion":"5.2",
		"HardwareVersion":"1.9.1.10-1",
		"IPAddress":"192.168.1.57",
		"MACAddress":"XX:XX:XX:XX:XX:52",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"21"}
`- topology: 	[{"group":"RINCON_B8E9373F4C5601400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.60:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"8",
		"uuid":"RINCON_B8E9373F4C5601400",
		"name":"Living Room"},{"group":"RINCON_B8E9373D977201400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.59:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"6",
		"uuid":"RINCON_B8E9373D977201400",
		"name":"Living Room"},{"group":"RINCON_B8E9370263F801400:0",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.56:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9370263F801400",
		"name":"BOOST"},{"group":"RINCON_B8E93761513001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.58:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"4",
		"uuid":"RINCON_B8E93761513001400",
		"name":"Living Room"},{"group":"RINCON_B8E9377A0F5201400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.57:1400/xml/device_description.xml",
		"version":"28.1-83251",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9377A0F5201400",
		"name":"Living Room"}]

Device 	{"host":"192.168.1.60","port":1400,"state":{}} (ZPS3)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"28.1-83040",
		"DisplaySoftwareVersion":"5.2",
		"HardwareVersion":"1.8.1.3-1",
		"IPAddress":"192.168.1.60",
		"MACAddress":"XX:XX:XX:XX:XX:56",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E9370263F801400:0",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.56:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9370263F801400",
		"name":"BOOST"},{"group":"RINCON_B8E9377A0F5201400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.57:1400/xml/device_description.xml",
		"version":"28.1-83251",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9377A0F5201400",
		"name":"Living Room"},{"group":"RINCON_B8E93761513001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.58:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"4",
		"uuid":"RINCON_B8E93761513001400",
		"name":"Living Room"},{"group":"RINCON_B8E9373D977201400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.59:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"6",
		"uuid":"RINCON_B8E9373D977201400",
		"name":"Living Room"},{"group":"RINCON_B8E9373F4C5601400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.60:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"8",
		"uuid":"RINCON_B8E9373F4C5601400",
		"name":"Living Room"}]

Device 	{"host":"192.168.1.59","port":1400,"state":{}} (ZPS3)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"28.1-83040",
		"DisplaySoftwareVersion":"5.2",
		"HardwareVersion":"1.8.1.3-1",
		"IPAddress":"192.168.1.59",
		"MACAddress":"XX:XX:XX:XX:XX:72",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E9373F4C5601400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.60:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"8",
		"uuid":"RINCON_B8E9373F4C5601400",
		"name":"Living Room"},{"group":"RINCON_B8E9370263F801400:0",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.56:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9370263F801400",
		"name":"BOOST"},{"group":"RINCON_B8E9377A0F5201400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.57:1400/xml/device_description.xml",
		"version":"28.1-83251",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"3",
		"uuid":"RINCON_B8E9377A0F5201400",
		"name":"Living Room"},{"group":"RINCON_B8E93761513001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.58:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"4",
		"uuid":"RINCON_B8E93761513001400",
		"name":"Living Room"},{"group":"RINCON_B8E9373D977201400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"channelfreq":"5805",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.59:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"6",
		"uuid":"RINCON_B8E9373D977201400",
		"name":"Living Room"}]

**Comment by ITechGuy** [comment]
Searching for Sonos devices on network...
/usr/local/lib/node_modules/airsonos/lib/main.js:30
    devices.forEach(function(device) {
           ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/airsonos/lib/main.js:30:12
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:105:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:129:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:129:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:575:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14

**Comment by tapetum** [comment]
Exact same error for me. I couldn't find a solution either.

**Comment by jfrolick** [comment]
Oddly enough, I tried to install this on a mac running Yosemite, and it worked perfectly.  I also tried installing it on a VM running Centos 7, and it froze after the "Searching for Sonos devices on network..." message.  The app was hung waiting on a system call.  I can't remember which one, but I think it was waiting on a read.  I can send an update later.

**Comment by jdewell** [comment]
Exactly the same error here. I've been looking into it. Oddly, I only get this error on my new macbook pro running osx yosemite 10.10.3 My old macbook also running yosemite 10.10.3 doesnt have this problem.

**Comment by diego-** [comment]
also having this issue on 10.10.3 with node 0.12.2

**Comment by martinverup** [comment]
Same issue here.
Node 12.2
OS X 10.10.3

**Comment by awolfend** [comment]
I am getting this issue with Yosemite 10.10.3 is a VM Ware Fusion VM.

**Comment by alfonssocken** [comment]
Got the same problem on my raspberry.
Node v0.12.1
Raspbian GNU/Linux 7

**Comment by alfonssocken** [comment]
When i set diagnostic true, airsonos can find my devices.
AirSonos Diagnostics
node version     v0.12.1
operating sys    linux (arm)
ip address       192.168......

Searching for Sonos devices on network...

Device  {"host":"192.168.......","port":1400,"state":{}} (ZPS3)
[...]

**Comment by manshurtigh** [comment]
How did you solve this?

**Comment by manshurtigh** [comment]
Seems like you can bypass this problem. Please see https://github.com/stephen/airsonos/pull/131. Worked like a charm!

**Comment by jensm** [comment]
Getting the same error on Raspberry Pi
pi@raspberrypi ~ $ sudo airsonos
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Searching for Sonos devices on network...
/usr/local/lib/node_modules/airsonos/lib/main.js:30
    devices.forEach(function(device) {
           ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/airsonos/lib/main.js:30:12
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:105:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
pi@raspberrypi ~ $

**Comment by siddharthm83** [comment]
The bypass did not work for me. i set diagnostics to true and seems like the devices are found but foreach still returns null 

airsonos
AirSonos Diagnostics
node version	 v0.12.7
operating sys	 darwin (x64)
ip address	 10.0.0.5

Searching for Sonos devices on network...

Device 	{"host":"10.0.0.15","port":1400,"state":{}} (ZPS9)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"29.5-91030",
		"DisplaySoftwareVersion":"5.4",
		"HardwareVersion":"1.9.1.10-1",
		"IPAddress":"10.0.0.15",
		"MACAddress":"XX:XX:XX:XX:XX:2B",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"21"}
`- topology: 	[{"group":"RINCON_B8E937BE42F401400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5765",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.17:1400/xml/device_description.xml",
		"version":"29.5-91030",
		"mincompatibleversion":"28.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"7",
		"uuid":"RINCON_B8E937BE42F401400",
		"name":"Living Room"},{"group":"RINCON_B8E937BD7D6A01400:3",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5765",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.16:1400/xml/device_description.xml",
		"version":"29.5-91030",
		"mincompatibleversion":"28.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"7",
		"uuid":"RINCON_B8E937BD7D6A01400",
		"name":"Living Room"},{"group":"RINCON_000E589B087201400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5765",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.18:1400/xml/device_description.xml",
		"version":"29.5-91030",
		"mincompatibleversion":"28.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"10",
		"uuid":"RINCON_000E589B087201400",
		"name":"Living Room"},{"group":"RINCON_B8E937BD7DF801400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.19:1400/xml/device_description.xml",
		"version":"29.5-91030",
		"mincompatibleversion":"28.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"4",
		"uuid":"RINCON_B8E937BD7DF801400",
		"name":"Master Bedroom"},{"group":"RINCON_000E5866E85401400:0",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.2:1400/xml/device_description.xml",
		"version":"29.5-90191",
		"mincompatibleversion":"28.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"17",
		"uuid":"RINCON_000E5866E85401400",
		"name":"BRIDGE"},{"group":"RINCON_000E58B7172B01400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.15:1400/xml/device_description.xml",
		"version":"29.5-91030",
		"mincompatibleversion":"28.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"10",
		"uuid":"RINCON_000E58B7172B01400",
		"name":"Living Room"}]
