### ISSUE TITLE
OS X Yosemite - Won't run AirSonos

### ISSUE THREAD

**Issue by gillsy** [stephen/airsonos#152]
Hi, 

Thanks for a great looking app, I have successlly installed it from NPM and run the $ npm install airsonos -g and it said successful.

However when I run it from terminal it says can't be found 

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'airsonos' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ 'airsonos', null ]
5 verbose cache add spec airsonos
6 silly cache add parsed spec { raw: 'airsonos',
6 silly cache add   scope: null,
6 silly cache add   name: 'airsonos',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed airsonos@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'airsonos', range: '*', hasData: false }
11 silly mapToRegistry name airsonos
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/airsonos
15 verbose addNameRange registry:https://registry.npmjs.org/airsonos not in flight; fetching
16 verbose request uri https://registry.npmjs.org/airsonos
17 verbose request no auth needed
18 info attempt registry request try #1 at 12:44:39 AM
19 verbose request id 1f84df424a84f88d
20 verbose etag "EBEKW18K9JDHJIYC1M0O360LC"
21 http request GET https://registry.npmjs.org/airsonos
22 http 304 https://registry.npmjs.org/airsonos
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 17 Apr 2015 14:44:40 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Fri, 17 Apr 2015 14:44:40 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"EBEKW18K9JDHJIYC1M0O360LC"',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-jfk1020-JFK',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1429281880.902148,VS0,VE36',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/airsonos from cache
25 verbose get saving airsonos to /Users/DavidWork/.npm/registry.npmjs.org/airsonos/.cache.json
26 silly addNameRange number 2 { name: 'airsonos', range: '*', hasData: true }
27 silly addNameRange versions [ 'airsonos',
27 silly addNameRange   [ '0.0.1',
27 silly addNameRange     '0.0.2',
27 silly addNameRange     '0.0.3',
27 silly addNameRange     '0.0.4',
27 silly addNameRange     '0.0.5',
27 silly addNameRange     '0.0.6',
27 silly addNameRange     '0.0.7',
27 silly addNameRange     '0.0.8',
27 silly addNameRange     '0.0.9',
27 silly addNameRange     '0.0.10',
27 silly addNameRange     '0.0.11',
27 silly addNameRange     '0.0.12',
27 silly addNameRange     '0.0.13',
27 silly addNameRange     '0.0.14',
27 silly addNameRange     '0.0.15',
27 silly addNameRange     '0.0.16',
27 silly addNameRange     '0.0.17',
27 silly addNameRange     '0.0.18',
27 silly addNameRange     '0.0.19',
27 silly addNameRange     '0.0.20',
27 silly addNameRange     '0.0.21',
27 silly addNameRange     '0.0.22',
27 silly addNameRange     '0.0.23',
27 silly addNameRange     '0.0.24',
27 silly addNameRange     '0.0.25',
27 silly addNameRange     '0.0.26',
27 silly addNameRange     '0.1.0',
27 silly addNameRange     '0.1.1' ] ]
28 verbose addNamed airsonos@0.1.1
29 silly addNamed semver.valid 0.1.1
30 silly addNamed semver.validRange 0.1.1
31 silly cache afterAdd airsonos@0.1.1
32 verbose afterAdd /Users/DavidWork/.npm/airsonos/0.1.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/DavidWork/.npm/airsonos/0.1.1/package/package.json written
34 silly install resolved [ { name: 'airsonos',
34 silly install resolved     version: '0.1.1',
34 silly install resolved     author: { name: 'Stephen Wan', email: 'stephen@stephenwan.net' },
34 silly install resolved     description: 'AirTunes to Sonos devices',
34 silly install resolved     contributors: [ [Object] ],
34 silly install resolved     scripts: { start: 'node ./index.js' },
34 silly install resolved     bin: { airsonos: './index.js' },
34 silly install resolved     global: 'true',
34 silly install resolved     repository: { type: 'git', url: 'https://github.com/stephen/airsonos.git' },
34 silly install resolved     dependencies:
34 silly install resolved      { flags: '~0.1.2',
34 silly install resolved        ip: '0.3.2',
34 silly install resolved        lodash: '~2.4.1',
34 silly install resolved        nicercast: '0.0.8',
34 silly install resolved        nodetunes: '0.1.2',
34 silly install resolved        portastic: '0.0.1',
34 silly install resolved        sonos: 'git://github.com/stephen/node-sonos.git#stephen-1.0.0',
34 silly install resolved        throttle: '~1.0.3' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     gitHead: '5467eb4186c42c93242339934e5c173165f1e0d4',
34 silly install resolved     bugs: { url: 'https://github.com/stephen/airsonos/issues' },
34 silly install resolved     homepage: 'https://github.com/stephen/airsonos',
34 silly install resolved     _id: 'airsonos@0.1.1',
34 silly install resolved     _shasum: '5d17b5ee88b7b9006e37f9ec86309a85c0c3b057',
34 silly install resolved     _from: 'airsonos@*',
34 silly install resolved     _npmVersion: '1.4.28',
34 silly install resolved     _npmUser: { name: 'swan', email: 'stephen@stephenwan.net' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '5d17b5ee88b7b9006e37f9ec86309a85c0c3b057',
34 silly install resolved        tarball: 'http://registry.npmjs.org/airsonos/-/airsonos-0.1.1.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/airsonos/-/airsonos-0.1.1.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install airsonos@0.1.1 into /usr/local/lib
36 info installOne airsonos@0.1.1
37 verbose installOne of airsonos to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/DavidWork/.npm/_locks/airsonos-8ac694bed89c8bf0.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/DavidWork/.npm/_locks/airsonos-8ac694bed89c8bf0.lock failed { [Error: EACCES, open '/Users/DavidWork/.npm/_locks/airsonos-8ac694bed89c8bf0.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/DavidWork/.npm/_locks/airsonos-8ac694bed89c8bf0.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/airsonos, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1004:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1008:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/DavidWork
41 error Darwin 14.1.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "airsonos"
43 error node v0.12.2
44 error npm  v2.7.4
45 error Attempt to unlock /usr/local/lib/node_modules/airsonos, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
 
Davids-MacBook-Air:~ DavidWork$ airsonos
-bash: airsonos: command not found
Davids-MacBook-Air:~ DavidWork$

**Comment by mattijsbliek** [comment]
It looks like the airsonos directory is not in the $PATH of your profile. Take a look at this StackOverflow question for more info:
https://stackoverflow.com/questions/15846076/command-not-found-after-installation

If you haven't changed anything to your shell, your $PATH should be in the `~/.bash_profile` file.

**Comment by stephen** [comment]
Given the `EACCESS`, you should also be running npm install with sudo, e.g. `sudo npm install -g airsonos`.
