### ISSUE TITLE
Airsonos & AppleTV

### ISSUE THREAD

**Issue by ambledown** [stephen/airsonos#153]
Just wanted to drop a note to let you know of an issue I came across this evening. 

I have been messing around with a new set of outdoor speakers and a Sonos:Connect Amp. I attempted to send the audio from an AppleTV to those speakers via Airsonos. While at first it appeared to connect, even going as far as showing the Volume selection, the loading circle continued to spin and the connection eventually seemed to time out. Then the speaker output selection returned to the original output of the AppleTV. 

Would love to see about getting the AppleTV to be able to select an Airsonos speaker as its audio output. Let me know if I can provide any information to help figure it out.

**Comment by pgeschke** [comment]
Hey John! Just out of interest - what speakers were those? Im looking for durable outdoor speakers :)

**Comment by ambledown** [comment]
I have a pair of these and they sound great...http://www.htd.com/Products/Outdoor-Speakers/Q65-Outdoor-Speakers

**Comment by pgeschke** [comment]
Ah alright! I thought those were airplay speakers too :)

**Comment by ambledown** [comment]
No. Just hooked up to a Sonos Connect:Amp and trying to connect via Airplay with Airsonos.

**Comment by tdmoreno** [comment]
I would also love to see airsonos allow for this functionality. I have also tried setting airsonos as the audio output for apple tv3. The airsonos speakers do populate the output menu but as the op noted the connection seems to time out.

**Comment by stephen** [comment]
Hmm, a verbose log would be useful in diagnosing - if one of you could run `airsonos --verbose` and paste the output when attempting to connect, here.

**Comment by jiji2x** [comment]
Hi

I am having the same issue with Apple TV. Works for a while, and then times out.

Another issue I am facing with ATV seems to be with the Airplay Mirroring option: when I use Airplay Mirroring, there doesn't seem to be any sound output transmitted to Airsonos.

I will run the airsonos --verbose log tonight and post the output tomorrow.

Thanks

**Comment by ambledown** [comment]
Sorry for the delay. Here is my verbose log:

Last login: Fri Aug 14 14:28:47 on ttys000
Server:~ joshsundquist$ airsonos --verbose
Searching for Sonos devices on network...
Setting up AirSonos for Patio {10.0.1.2:1400}
  nodetunes:server starting nodetunes server (Patio (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +17ms
Setting up AirSonos for Master Bedroom {10.0.1.6:1400}
  nodetunes:server starting nodetunes server (Master Bedroom (AirSonos)) +4ms
  nodetunes:server broadcasting mdns advertisement (for port 5001) +9ms
Setting up AirSonos for Patio {10.0.1.2:1400}
  nodetunes:server starting nodetunes server (Patio (AirSonos)) +5ms
  nodetunes:server broadcasting mdns advertisement (for port 5002) +9ms
Setting up AirSonos for Master Bedroom {10.0.1.6:1400}
  nodetunes:server starting nodetunes server (Master Bedroom (AirSonos)) +5ms
  nodetunes:server broadcasting mdns advertisement (for port 5003) +11ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x7cd1c30af130',
  'apple-challenge': '8yiWcGLKu89FsdDNYNnLTA==',
  'dacp-id': '1FC2BA567DA05D32',
  'active-remote': '3541430384',
  'user-agent': 'AirPlay/220.68',
  'content-length': '0' } +21s
  nodetunes:helper building challenge for 8yiWcGLKu89FsdDNYNnLTA== (ip: 0a000165, mac: 5452005af70f) +1ms
  nodetunes:helper computed challenge: KeJGhYhjZqK/muwhYNh6vkE+rBMtR04WMJCV6OeJ2S1NJmgl2ayuPgl1GjOClCXyJyakLxD8wUuGvNVX6eeAiTCloVeZpncUn/a6Z6kHxXVkM92bKfvMys6xZMUX3X6sLCaljStWsoI/WGdTlbFbkhzObM1zkqDItbUArjofQ+nSQxGoAca2SLuHnrS5Ss0CBooVMR3ieUprULpSL0AHPW46cRFxRzuC0iCp7qjRK0yMsWWArew8O7rxh7t1qMYnmG0Zav7OzBeTQCAxEeYalscoQMLk2YRPnmFy+jWbXvj49W2JuWjOseiUzY4nGIj7AHh/S2GJr38/iThDa+/l0g== +98ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x7cd1c30af130',
  'apple-challenge': 'lT7/FrlHhcayQSxGQMsy1w==',
  'dacp-id': '1FC2BA567DA05D32',
  'active-remote': '1686366408',
  'user-agent': 'AirPlay/220.68',
  'content-length': '0' } +1m
  nodetunes:helper building challenge for lT7/FrlHhcayQSxGQMsy1w== (ip: 0a000165, mac: 545200c0aa19) +1ms
  nodetunes:helper computed challenge: rEQyZPdToEzHcoBk/GjPyQDJ1Lf68NYzMZeYmdDm+4EXGskObcvQQtWVEdd6943d1pBGjmOU0sC/5rlDgyWEtrtwKrwTF0/zo9veGeLrY04mGRIGauZFznAcHxzwaZlCU1/c2+ENjutxD9EbWF1ya4tSNMCTLcrJjJBn7PFQsWbEHuZuguZmkchu8UjJQRjdBOmf1tJCAMZfHyLMw4ZNrlYfRc/wsJATROfnFzvgYHJwuprNQhE1nXDsdepM2I7Km6Uyz9Cs1E1dhp3UVcSwllZ76PncboFeBypXXtS9bUW3kakx3xDyRElVpgcX95dLws6LXzXvbn4euEmIO/9LpQ== +71ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x7cd1c30af130',
  'apple-challenge': 'lBJ7hpS5yQUKXBJqdHjU9Q==',
  'dacp-id': '1FC2BA567DA05D32',
  'active-remote': '3004891716',
  'user-agent': 'AirPlay/220.68',
  'content-length': '0' } +24s
  nodetunes:helper building challenge for lBJ7hpS5yQUKXBJqdHjU9Q== (ip: 0a000165, mac: 5452004c789f) +1ms
  nodetunes:helper computed challenge: f32rO/Bh+trKhNbdhF0HdD6bRAgPQiPI60VTzc/9aYbmOjUwFwWD6qi/cv7NfrvbO1sM0LY18MvaAukbme4feC1nLoVx/n1cmZcmOZ29b4M1IrEeBMmno7ur0sqPEv2MUQ+hgWlmZGGKH3wgxpehHDmH1wqM286Lcq4mEUj/dWs+g0NarnujkKY2ucSqPJtRZeDz0Hm9O8FM8Rv+WsBxdHolG2RMzGFyN7vC5lqQ9OVM/N5OCGPHfu09yaMjk2Sh70IgdrajrvL1MS4ILvmsIjAHhjON0H20B0Fcih/TUGX4XHY3LDWhqPXCDh6bmA8lZTQT7/lgYBf0FkpgyG3WOw== +63ms

**Comment by stephen** [comment]
This might be an issue that's been fixed in 0.2.2 (release today). Could try again with the verbose output and report back? Also, which version of node are you using? (`node --version`)

**Comment by ambledown** [comment]
Fixed with today's release! Thank you for all of your hard work! Love to see Airsonos becoming such an awesome solution!
