### ISSUE TITLE
Problems with OSX Yosemite

### ISSUE THREAD

**Issue by Shemahmforash** [stephen/airsonos#155]
First of all, congratulations on creating this great hack for using airplay capabilities with sonos. 
I haven't managed to successfully use it, though. The installation and running of the script works perfectly well, and I can see my sonos system in the list of output devices, although when I try to select it as the output audio device it says "Could not connect to “Living Room (AirSonos)”" without further information. If I select it as the output device from the itunes application it tells me: "The AirPlay device “Living Room (AirSonos)” is not compatible with this version of iTunes."

Is there a way I can debug this?

**Comment by pgeschke** [comment]
Hey Shemahmforash!

Airsonos has a verbose output and diagnostics mode.
Maybe you could run it like this

#> airsonos --verbose --diagnostics

and then post the output here, so you and other people maybe have a hint to what's going on.

**Comment by Shemahmforash** [comment]
It now works perfectly :) It was weird, because I haven't done anything different since yesterday besides restarting OS X. Thanks a lot for your help anyway!

**Comment by pgeschke** [comment]
That sounds great!

**Comment by Shemahmforash** [comment]
yes, both working perfectly!

**Comment by pgeschke** [comment]
Okay, great for you!

**Comment by Shemahmforash** [comment]
I don't know much about node.js nor the protocols to help in the development. Although I will for sure recommend this project to my friends.
