### ISSUE TITLE
Will not work

### ISSUE THREAD

**Issue by Nabk6** [stephen/airsonos#158]
It shows up on the sonos app, but when i click play it says 

unable to play 'airsonos' - unable to connect to 192.168.2.21:8000
![screen shot 2015-04-22 at 7 01 52 pm](https://cloud.githubusercontent.com/assets/11491653/7287391/1d6a4e42-e922-11e4-8a6d-392ecbbbdda2.png)

**Comment by pand1g1tal** [comment]
As I understand it you don't connect via the Sonos App - use Airplay on your device instead

**Comment by Nabk6** [comment]
When I try to use airplay on the deive everything becomes all messed up and i get an error saying: 
![screen shot 2015-04-23 at 10 09 52 pm](https://cloud.githubusercontent.com/assets/11491653/7311102/87413900-ea05-11e4-930e-1f2de291ed69.png)
