### ISSUE TITLE
Unable to Install on Snow Leopard

### ISSUE THREAD

**Issue by musiclover12** [stephen/airsonos#160]
Hello,

I am very keen to install airsonos to run on my 2010 iMac running snow leopard with two Play 1 speakers. I have followed the instructions online to the letter but I can't seem to get things working. 

The redacted Terminal print out is below. I would be very grateful for any help anyone can provide and would be willing to pay a reasonable fee for someone to set up airsonos on my computer using TeamViewer.

Last login: Thu Apr 23 20:17:29 on ttys000
XXXXX-iMac:~ XXXXX$ $ npm install airsonos -g
-bash: $: command not found
XXXXX-iMac:~ XXXXX$ $ npm install airsonos -g
-bash: $: command not found
XXXXX-iMac:~ XXXXX$ npm install airsonos -g
npm ERR! tar.unpack untar error /Users/XXXXX/.npm/airsonos/0.1.1/package.tgz
npm ERR! Darwin 10.8.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /usr/local/lib/node_modules/airsonos
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXXX/npm-debug.log
XXXXX-iMac:~ XXXXX$ 
XXXXX-iMac:~ XXXXX$ git clone https://github.com/stephen/airsonos.git
-bash: git: command not found
XXXXX-iMac:~ XXXXX$ npm install airsonos -g
npm ERR! tar.unpack untar error /Users/XXXXX/.npm/airsonos/0.1.1/package.tgz
npm ERR! Darwin 10.8.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /usr/local/lib/node_modules/airsonos
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXXX/npm-debug.log
XXXXX-iMac:~ XXXXX$ npm install airsonos -g
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/XXXXX
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/XXXXX/npm-debug.log
npm ERR! not ok code 0
XXXXX-iMac:~ XXXXX$ defaults write com.apple.finder AppleShowAllFiles TRUE
XXXXX-iMac:~ XXXXX$ killall Finder
XXXXX-iMac:~ XXXXX$ sudo rm /usr/local/bin/npm
Password:
XXXXX-iMac:~ XXXXX$ sudo rm /usr/local/bin/npm
rm: /usr/local/bin/npm: No such file or directory
XXXXX-iMac:~ XXXXX$ sudo rm /usr/local/share/man/man1/node.1
XXXXX-iMac:~ XXXXX$ sudo rm /usr/local/lib/dtrace/node.d
XXXXX-iMac:~ XXXXX$ sudo rm -rf ~/.npm
XXXXX-iMac:~ XXXXX$ sudo rm -rf ~/.node-gyp
XXXXX-iMac:~ XXXXX$ sudo rm /opt/local/bin/nod
rm: /opt/local/bin/nod: No such file or directory
XXXXX-iMac:~ XXXXX$ sudo rm /opt/local/include/node
rm: /opt/local/include/node: No such file or directory
XXXXX-iMac:~ XXXXX$ sudo rm -rf /opt/local/lib/node_modules
XXXXX-iMac:~ XXXXX$ npm install airsonos -g
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/XXXXX
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/XXXXX/npm-debug.log
npm ERR! not ok code 0
XXXXX-iMac:~ XXXXX$

**Comment by pand1g1tal** [comment]
have you installed node js?

**Comment by musiclover12** [comment]
Yes.

**Comment by pand1g1tal** [comment]
Did you try sudo install ?

**Comment by musiclover12** [comment]
I think so. The terminal line should be: 

$ sudo npm install airsonos -g ???

Many thanks.

**Comment by pand1g1tal** [comment]
Try this instead - worked for me - http://sonoair.mihosoft.eu/

**Comment by musiclover12** [comment]
Thank you very much for the tip. It seems to be working.
