### ISSUE TITLE
Wont Setup

### ISSUE THREAD

**Issue by DarraghWalsh** [stephen/airsonos#162]
The Terminal says
Last login: Sat Apr 25 18:29:49 on ttys000

Welcome To Terminal, 
DarraghWalsh

     April 2015
Su Mo Tu We Th Fr Sa
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30

DarraghWalsh:sudo airsonos
Password:
Searching for Sonos devices on network...
Setting up AirSonos for Living Room {192.168.0.15:1400}

Thats all, it won't do ANYTHING after that issue.

**Comment by davidjbradshaw** [comment]
That is all it does, you need then connect to it from an iOS device. You might need to restart everything the first time.

**Comment by stephen** [comment]
This is the intended behavior - you should be able to see the AirPlay devices from OS X Sound Preferences.
