### ISSUE TITLE
Mac doesn't see AirSonos speakers after install/run

### ISSUE THREAD

**Issue by meichner** [stephen/airsonos#163]
Stephen,

First, thanks for sharing this program with the community.  I'm using Band-in-a-Box on my Mac for musical accompaniment, and if this works to port it to my home Sonos speakers, it would be a huge boost for practice time.

The issue I'm seeing.  I'm on Yosemite 10.10.3, and have run the install program.  I run the airsonos at the prompt, and it says "Setting up AirSonos for .." for lots of speakers.  But then...I don't see any AirSonos speaker options in the /Preferences/Sound dialog.  Has this happened before?  Any advice?

Thanks in advance for your help!
Matt.

**Comment by FpazHn** [comment]
The same happens to me. I installed airsonos in my synology. It finds all the sonos speakers (twice) but they are not found on my mac or my ios devices. 

Dont know if its my installation or the router. 

I tried to change my nodejs version but i just cant seem to secceed at it. 

Thanks if anybody could help.

**Comment by KarimGeiger** [comment]
Same here.

When running in diagnostics mode, it outputs my system (one Play 1-Speaker) correctly. After that, nothing happens.

````
$ airsonos --verbose --diagnostics
AirSonos Diagnostics
node version	 v0.12.2
operating sys	 darwin (x64)
ip address	 127.94.0.1

Searching for Sonos devices on network...

Device 	{"host":"192.168.13.29","port":1400,"state":{}} (ZPS1)
`- attrs: 	{"CurrentZoneName":"Wohnzimmer",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"28.1-83040",
		"DisplaySoftwareVersion":"5.2",
		"HardwareVersion":"1.8.3.7-2",
		"IPAddress":"192.168.13.29",
		"MACAddress":"XX:XX:XX:XX:XX:XX",
		"CopyrightInfo":"© 2004-2014 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E93783936CXXXX:1",
		"coordinator":"true",
		"wirelessmode":"1",
		"channelfreq":"2462",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.13.29:1400/xml/device_description.xml",
		"version":"28.1-83040",
		"mincompatibleversion":"27.0-00000",
		"legacycompatibleversion":"24.0-0000",
		"bootseq":"20",
		"uuid":"RINCON_B8E93783936CXXXX",
		"name":"Wohnzimmer"}]````

**Comment by ElDigitalDon** [comment]
I am seeing a similar issue.  I get two Devices, my two Play:1 speakers, but nothing appears after that, not sure what is going or what to troubleshoot.

**Comment by haggyish** [comment]
My results on OS X 10.11:
hagmac:airsonos-master hag$ airsonos --verbose
Searching for Sonos devices on network...
/usr/local/lib/node_modules/airsonos/lib/main.js:30
    devices.forEach(function(device) {
           ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/airsonos/lib/main.js:30:12
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:105:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
hagmac:airsonos-master hag$

**Comment by stephen** [comment]
node 0.12 wasn't supported until airsonos 0.2.2. Can you upgrade and try again?
