### ISSUE TITLE
Getting Permission denied error when trying to load

### ISSUE THREAD

**Issue by scottwvw** [stephen/airsonos#164]
Any ideas what I need to do?
```
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.8.4 /usr/local/lib/node_modules/npm
Scotts-MacBook-Pro:~ scottvanwinden$ sudo npm install airsonos -g
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
 
> mdns@2.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
 
> lame@1.2.1 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.10.33
npm ERR! npm  v2.8.4
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! lame@1.2.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lame@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scottvanwinden/npm-debug.log
```

**Comment by davidjbradshaw** [comment]
`sudo npm i -g airsonos`

**Comment by legba42** [comment]
After a fresh boot, I'm getting similar results, below is the output from: sudo npm i -g airsonos

npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
 
> mdns@2.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found
/
> lame@1.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-gyp: command not found

npm ERR! mdns@2.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the mdns@2.2.2 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "-g" "airsonos"
npm ERR! cwd /Users/brian

**Comment by stephen** [comment]
This looks like an issue related to your node-gyp installation, not airsonos directly. Also see: https://github.com/TooTallNate/node-gyp/issues/115#issuecomment-28490552
