### ISSUE TITLE
Asks for password on airsonos install

### ISSUE THREAD

**Issue by jvt3001** [stephen/airsonos#165]
Having issues getting airsonos install. after sudo npm install nodetunes -g 
asks for password

**Comment by sportsnapper** [comment]
You're running sudo - so you need to supply the root password to get the install to work.

**Comment by jvt3001** [comment]
Sorry, I have no idea how most of this stuff works. What is a root password
and where can I obtain it?

**Comment by sportsnapper** [comment]
It will be your admin password - but, if you're not up to speed understanding sudo/root you may want to have a bit of look at some basic tutorials on linux/unix - otherwise you'll be stuck at every step. This is not  a beginners project IMHO...

**Comment by jstdx** [comment]
I use SonoAir (http://sonoair.mihosoft.eu/) which comes with a graphical user interface. The downside is that it is a relatively big application since it uses Java + java-sonos and Node + AirSonos but it works great for me and it is super easy to install.
