### ISSUE TITLE
Problem loading shared library when starting with init.d

### ISSUE THREAD

**Issue by dbdrwdn** [stephen/airsonos#166]
Hello,
i try to setup airsonos on my PI2 to start on boot (retropie -> raspbian).
I'm able to start airsonos from the commandline and via a generated init-script (pleaserun) from the commandline without problems.
The only thing that does not work, is to start on boot (same script, just not started via commandline).
The error log says that a shared library can not be loaded: dns_sd_bindings.node

Is there any advice what i maybe need to add to my init-script to get airsonos to start on boot?

Thx, daniel

**Comment by davidjbradshaw** [comment]
Use `/etc/rc.local` as the location to start it from.
