### ISSUE TITLE
Question on how to Diagnose issues

### ISSUE THREAD

**Issue by jeeftor** [stephen/airsonos#167]
I'm having issues with AirSonos which are likely related to my network but I'm wondering about the best way to go about diagnosing the issue.  

I successfully see (multiple) copies of the various airplay devices yet when I attempt to play to a source nothing "seems" to work.  When running with **-verbose** I get output similar to:  

```
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x78fd94975a01',
  'apple-challenge': 'uXTUGeA0ECpWOI6tjFi+zA==',
  'dacp-id': '35AFFCAA063A4820',
  'active-remote': '3014227415',
  'user-agent': 'AirPlay/220.68',
  'content-length': '0' } +2m
  nodetunes:helper building challenge for uXTUGeA0ECpWOI6tjFi+zA== (ip: c0a80191, mac: 54520001e5a6) +1ms
  nodetunes:helper computed challenge: gOHBVW0WZ4Okn3vfBl9741j8EHXm2tz8KAEX9rbNw0e/HlLj6EzORsBB1UqyFnkZOJw4Y3yUCkPqROmFpTYebojBaCjtqAYSvpgv8IRU/sy1mlIRepFBN7VcOlo6A+PQRixvCVATNYOMRLVamA6Qjp+gu/Mj8D93udyWkF/6/P9ujnqd2BXpBR0vAW1N2Y9+RRfur8PRVJvlE5fHzMon7EYKAFQKAcg0HTg6lv/KGLcg5czfSiKm8b+/wIPPagks/TmlRqwn75kTbipLUMLACvmbUqqcNNhUTkOlRLJ1PKcl4xJIRcxZWt/exmFQIzczwAt0leMDx6/N78sZgKGHFA== +74ms
```

Could somebody post what it is supposed to look like with verbose mode if a connection IS successful.  

I'm wondering if its  network latency issue - perhaps the +74ms is too slow?  I do have a 100+ yr old house which has TERRIBLE wifi performance.

**Comment by stephen** [comment]
What version of node are you using? Is that the entirety of the output you see?
