### ISSUE TITLE
Sonos Controller 5.4 Beta breaks Airsonos after update

### ISSUE THREAD

**Issue by awolfend** [stephen/airsonos#169]
Since updating Sonos Controller to latest 5.4 beta today, i get the following messages when trying to play iTunes audio via airsonos:

"An error occurred while connecting to the Airplay Device .... An Unknown Error occurred (-15000)."

Any ideas?

**Comment by awolfend** [comment]
Issue certainly made worse by any third party audio drivers on systems pushing content via airsonos.
Airparrot 2 appears to break Airsonos functionality when Airparrot Audio drivers are installed.  Removing Airparrot 2 lessens the impact.

**Comment by TimMeade** [comment]
I'm running the 5.4 beta and Airsonos just sits at Searching for Sonos devices on network...

**Comment by MartinAyla** [comment]
Any updates on this?

I can see that Sonos is rolling out the updated app today in the App Store.

**Comment by dbdrwdn** [comment]
I'm getting this error in iTunes too. But it started before 5.4
The error only occurs when using iTunes to connect. iOS and OSX system sound (including music played by iTunes) is no problem.
Try to connect using alt click on the volume icon in OSX.
