### ISSUE TITLE
Node 0.12 vs 0.10

### ISSUE THREAD

**Issue by jeeftor** [stephen/airsonos#173]
So I've been having a terrible experience with Airsonos until today when I downgraded to NODE 0.10 -> I think somewhere in the documentation it should be mentioned this runs better with 0.10

**Comment by JBlackCat** [comment]
I think it might make more sense to have a known issues section, rather than saying it works better with 0.10. 

Since the readme contains ```AirSonos requires node.js >= v0.10.33 installed to run.`` one can assume it will most likely run better on an earlier version, since there have been breaking changes between node 10 and 12.`

**Comment by evandy0** [comment]
Thanks for posting this!  I, too, was having issues with AirSonos on Node 0.12.x, but downgrading to the last 0.10 release (0.10.38) has cleared everything up nicely.  (Running on a 10.7.x MacMini OS X that's always on anyways).   Totally sad that Sonos won't pay the tax to integrate AirPlay directly, but at least this seems to fit the bill.

Will need to get it running automatically as a daemon at boot eventually.

**Comment by phylaxis** [comment]
Can you run AirSonos with a separate install of Node or is a downgrade required? I use Node for other things on my system and don't want to downgrade just for AirSonos.

**Comment by JBlackCat** [comment]
@phylaxis, remove the regular node install from your system. Assuming you are using OS X, here are instructions [http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x](http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x).

Then install NVM, [https://github.com/creationix/nvm](https://github.com/creationix/nvm).

Install as many versions of node as you like using NVM. The catch is any global modules you have installed, you will have to reinstall them for every version. But now you can easily switch between versions, install and uninstall. Supports io.js and node.

You can also ```brew install nvm``` but it is not supported by creationix, so it may or may not always be up-to-date and working correctly.

**Comment by sirLisko** [comment]
I suggest using n (https://github.com/tj/n) instead of nvm, I always had problem with nvm and how it handle the global modules is a bit crazy.

**Comment by mblakele** [comment]
In case it helps someone else, here are instructions for homebrew and OS X 10.0.5.

```
brew tap homebrew/versions
brew unlink node
brew install node010
```

Then rebuild airsonos:

```
npm uninstall -g airsonos
npm install -g airsonos
```

**Comment by stephen** [comment]
Now compatible with 0.12 - this should be less of a problem.
