### ISSUE TITLE
Raspberry 2 Model B issue

### ISSUE THREAD

**Issue by krizor** [stephen/airsonos#176]
Hi Stephen,

I just bought 2 Sonos speakers to since I found your airsonos application a great solution for my home entertainment. I am running a forked daapd server on a raspberry 2 Model B so I don't need a pc running for a itunes server.
I installed now the airsons which worked smooth without any problems.

root@raspberrypi:~/node-v0.10.33# node -v
v0.10.33
root@raspberrypi:~/node-v0.10.33# npm -v
1.4.28
root@raspberrypi:~/node-v0.10.33#

But when I try to play a song via itunes and send it to one of the sonos boxes which were recognized I get :

Warning! Codec not supported (96 AppleLossless)
AirSonos currently does not support codecs used by applications such as iTunes or AirFoil.
Progress on this issue: #1

Did you make any progress on the codec issue ? or do I have to go to a different version ?

thanks in advance

**Comment by stephen** [comment]
Any clients that use ALAC (iTunes, etc.) are not supported. See: https://github.com/stephen/nodetunes/issues/1
