### ISSUE TITLE
SONOS CONNECTS AND DISCONNECTS BUT NO MUSIC COMES OUT!

### ISSUE THREAD

**Issue by oaceprm** [stephen/airsonos#178]
Hi,

when i run airsonos this is what comes up: 

airsonos
Searching for Sonos devices on network...
Setting up AirSonos for Master Bedroom {10.0.0.57:1400}

i then click on the airsonos option on my iphone airplay and it connects when i try play music it disconnects and disappears. i have to run the terminal again and type airsonos to bring it back.

i have had no sucess so far with the airsonos because of this fault any help would be appreciated :)

**Comment by navynbs** [comment]
I'm facing exactly the same problem; recognizes the Sonos, select it, play, switches to the original device.
Searching for Sonos devices on network...
Setting up AirSonos for Living Room {10.0.1.6:1400}

the fact that the Sonos is recognised is awesome, getting it to play my files will be even better! any help is highly appreciated.

**Comment by HanSooloo** [comment]
I have the same issue on a OSX Yosemite system (10.10.3).

To install airsonos, I did the following:
1. Install npm via 'brew install npm'
2. Install airsonos via 'npm install airsonos -g'

**Comment by cwallen** [comment]
I had the same thing. Cause looks to be https://github.com/stephen/nodetunes/pull/29. Using Node 0.10 worked for me.

**Comment by HanSooloo** [comment]
I can confirm 0.10.28 did it for me as well.

**Comment by iDuuck** [comment]
-1 not working for me with 0.10

**Comment by timkendall** [comment]
Just installed latest Sonos update on my Play:3; using Node -v 0.10.28; shows `Setting up AirSonos for Living Room {10.0.1.2:1400}`; but no audio plays ;/ Sonos update must have broken something because this was working before.
