### ISSUE TITLE
Help... 

### ISSUE THREAD

**Issue by Ger5150** [stephen/airsonos#180]
Hi,

I get no sounds and all my sonos devices show up in threefold... 

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'airsonos', '-g' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'airsonos', null ]
7 verbose cache add spec airsonos
8 silly cache add parsed spec { raw: 'airsonos',
8 silly cache add   scope: null,
8 silly cache add   name: 'airsonos',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed airsonos@*
10 verbose addNamed "*" is a valid semver range for airsonos
11 silly addNameRange { name: 'airsonos', range: '*', hasData: false }
12 silly mapToRegistry name airsonos
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/airsonos
16 verbose addNameRange registry:https://registry.npmjs.org/airsonos not in flight; fetching
17 verbose request uri https://registry.npmjs.org/airsonos
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:23:21 PM
20 verbose request id 47834f3c8ec065b6
21 verbose etag "16CFSH0V9IT0IOEEGONBPMSL5"
22 http request GET https://registry.npmjs.org/airsonos
23 http 304 https://registry.npmjs.org/airsonos
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 15 Jun 2015 11:23:21 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"16CFSH0V9IT0IOEEGONBPMSL5"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-fra1245-FRA',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1434367401.827442,VS0,VE494',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/airsonos from cache
26 verbose get saving airsonos to /Users/GJvH/.npm/registry.npmjs.org/airsonos/.cache.json
27 silly addNameRange number 2 { name: 'airsonos', range: '*', hasData: true }
28 silly addNameRange versions [ 'airsonos',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.0.10',
28 silly addNameRange     '0.0.11',
28 silly addNameRange     '0.0.12',
28 silly addNameRange     '0.0.13',
28 silly addNameRange     '0.0.14',
28 silly addNameRange     '0.0.15',
28 silly addNameRange     '0.0.16',
28 silly addNameRange     '0.0.17',
28 silly addNameRange     '0.0.18',
28 silly addNameRange     '0.0.19',
28 silly addNameRange     '0.0.20',
28 silly addNameRange     '0.0.21',
28 silly addNameRange     '0.0.22',
28 silly addNameRange     '0.0.23',
28 silly addNameRange     '0.0.24',
28 silly addNameRange     '0.0.25',
28 silly addNameRange     '0.0.26',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1' ] ]
29 silly addNamed airsonos@0.1.1
30 verbose addNamed "0.1.1" is a plain semver version for airsonos
31 silly cache afterAdd airsonos@0.1.1
32 verbose afterAdd /Users/GJvH/.npm/airsonos/0.1.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/GJvH/.npm/airsonos/0.1.1/package/package.json written
34 silly install resolved [ { name: 'airsonos',
34 silly install resolved     version: '0.1.1',
34 silly install resolved     author: { name: 'Stephen Wan', email: 'stephen@stephenwan.net' },
34 silly install resolved     description: 'AirTunes to Sonos devices',
34 silly install resolved     contributors: [ [Object] ],
34 silly install resolved     scripts: { start: 'node ./index.js' },
34 silly install resolved     bin: { airsonos: './index.js' },
34 silly install resolved     global: 'true',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+https://github.com/stephen/airsonos.git' },
34 silly install resolved     dependencies:
34 silly install resolved      { flags: '~0.1.2',
34 silly install resolved        ip: '0.3.2',
34 silly install resolved        lodash: '~2.4.1',
34 silly install resolved        nicercast: '0.0.8',
34 silly install resolved        nodetunes: '0.1.2',
34 silly install resolved        portastic: '0.0.1',
34 silly install resolved        sonos: 'git://github.com/stephen/node-sonos.git#stephen-1.0.0',
34 silly install resolved        throttle: '~1.0.3' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     gitHead: '5467eb4186c42c93242339934e5c173165f1e0d4',
34 silly install resolved     bugs: { url: 'https://github.com/stephen/airsonos/issues' },
34 silly install resolved     homepage: 'https://github.com/stephen/airsonos',
34 silly install resolved     _id: 'airsonos@0.1.1',
34 silly install resolved     _shasum: '5d17b5ee88b7b9006e37f9ec86309a85c0c3b057',
34 silly install resolved     _from: 'airsonos@*',
34 silly install resolved     _npmVersion: '1.4.28',
34 silly install resolved     _npmUser: { name: 'swan', email: 'stephen@stephenwan.net' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '5d17b5ee88b7b9006e37f9ec86309a85c0c3b057',
34 silly install resolved        tarball: 'http://registry.npmjs.org/airsonos/-/airsonos-0.1.1.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/airsonos/-/airsonos-0.1.1.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install airsonos@0.1.1 into /usr/local/lib
36 info installOne airsonos@0.1.1
37 verbose installOne of airsonos to /usr/local/lib not in flight; installing
38 verbose lock using /Users/GJvH/.npm/_locks/airsonos-8ac694bed89c8bf0.lock for /usr/local/lib/node_modules/airsonos
39 silly install write writing airsonos 0.1.1 to /usr/local/lib/node_modules/airsonos
40 verbose unbuild lib/node_modules/airsonos
41 info preuninstall airsonos@0.1.1
42 info uninstall airsonos@0.1.1
43 verbose unbuild rmStuff airsonos@0.1.1 from /usr/local/lib/node_modules
44 silly gentlyRm /usr/local/bin/airsonos is being gently removed
45 silly gentlyRm verifying /usr/local is an npm working directory
46 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
47 silly gentlyRm deletion target /usr/local/bin/airsonos is under /usr/local
48 verbose gentlyRm vacuuming from /usr/local/bin/airsonos up to /usr/local
49 silly vacuum-fs removing /usr/local/bin/airsonos
50 verbose unlock done using /Users/GJvH/.npm/_locks/airsonos-8ac694bed89c8bf0.lock for /usr/local/lib/node_modules/airsonos
51 verbose stack Error: EACCES, unlink '/usr/local/bin/airsonos'
51 verbose stack     at Error (native)
52 verbose cwd /Users/GJvH
53 error Darwin 14.4.0
54 error argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
55 error node v0.12.4
56 error npm  v2.10.1
57 error path /usr/local/bin/airsonos
58 error code EACCES
59 error errno -13
60 error Error: EACCES, unlink '/usr/local/bin/airsonos'
60 error     at Error (native)
60 error  { [Error: EACCES, unlink '/usr/local/bin/airsonos'] errno: -13, code: 'EACCES', path: '/usr/local/bin/airsonos' }
61 error Please try running this command again as root/Administrator.
62 verbose exit [ -13, true ]
63 verbose unbuild lib/node_modules/airsonos
64 info preuninstall airsonos@0.1.1
65 info uninstall airsonos@0.1.1
66 verbose unbuild rmStuff airsonos@0.1.1 from /usr/local/lib/node_modules
67 silly gentlyRm /usr/local/bin/airsonos is being gently removed
68 silly gentlyRm verifying /usr/local is an npm working directory
69 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
70 silly gentlyRm deletion target /usr/local/bin/airsonos is under /usr/local
71 verbose gentlyRm vacuuming from /usr/local/bin/airsonos up to /usr/local
72 silly vacuum-fs removing /usr/local/bin/airsonos
73 error error rolling back Error: EACCES, unlink '/usr/local/bin/airsonos'
73 error error rolling back     at Error (native)
73 error error rolling back  { [Error: EACCES, unlink '/usr/local/bin/airsonos'] errno: -13, code: 'EACCES', path: '/usr/local/bin/airsonos' }

**Comment by davidjbradshaw** [comment]
Use Node 0.10.33, not 0.12.4.

**Comment by stephen** [comment]
0.12.4 is now compatible.
