### ISSUE TITLE
Fails to install if your home path has a space in it.

### ISSUE THREAD

**Issue by davidjbradshaw** [stephen/airsonos#181]
When installing via NPM I get the following error, which seems to be due to my home path being `/Volumes/Data SSD/Users/dave.

    npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
	 
	> mdns@2.2.2 install /private/tmp/airsonos/node_modules/nodetunes/node_modules/mdns
	> node-gyp rebuild

	make: *** No rule to make target `../../../../../../../../Volumes/Data', needed by `Makefile'.  Stop.
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
	gyp ERR! System Darwin 14.3.0
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /private/tmp/airsonos/node_modules/nodetunes/node_modules/mdns
	gyp ERR! node -v v0.10.38
	gyp ERR! node-gyp -v v1.0.3
	gyp ERR! not ok 
	 
	> lame@1.2.2 install /private/tmp/airsonos/node_modules/nicercast/node_modules/lame
	> node-gyp rebuild

	deps/mpg123/test.target.mk:147: warning: overriding commands for target `Release/test'
	deps/lame/test.target.mk:155: warning: ignoring old commands for target `Release/test'
	make: *** No rule to make target `../../../../../../../../Volumes/Data', needed by `Makefile'.  Stop.
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
	gyp ERR! System Darwin 14.3.0
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /private/tmp/airsonos/node_modules/nicercast/node_modules/lame
	gyp ERR! node -v v0.10.38
	gyp ERR! node-gyp -v v1.0.3
	gyp ERR! not ok 
	npm ERR! Darwin 14.3.0
	npm ERR! argv "node" "/usr/local/bin/npm" "i"
	npm ERR! node v0.10.38
	npm ERR! npm  v2.11.0
	npm ERR! code ELIFECYCLE

	npm ERR! lame@1.2.2 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the lame@1.2.2 install script 'node-gyp rebuild'.
	npm ERR! This is most likely a problem with the lame package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls lame
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /private/tmp/airsonos/npm-debug.log

**Comment by stephen** [comment]
This isn't caused by airsonos directly, but node-gyp: https://github.com/nodejs/node-gyp/issues/65

:disappointed: =
