### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Paul0102** [stephen/airsonos#186]
Hi there,

I'm trying to install Airsonos but it seems like I'm not that good at it. I installed node 0.10.33. But the rest doesnt work. There seems to be an access problem. Can someone give me any help ? I don't know what to do.

Thanks a lot !
Paul

MBP-de-Paul-3:~ Paul$ npm install airsonos -g
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/Paul
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Paul/npm-debug.log
npm ERR! not ok code 0

**Comment by saneld** [comment]
Try this:
sudo npm install airsonos -g
