### ISSUE TITLE
Unable to set airsonos on iTunes 12.2 running OS X Yosemite 10.10.4

### ISSUE THREAD

**Issue by va3lim** [stephen/airsonos#188]
Below is what I did:

a) Prior to running the command "sudo npm install airsonos -g", I downloaded and installed node-v0.12.6.pkg.  I verified if it is installed properly.

MacBook-Air-2010:Downloads mlim$ which node
/usr/local/bin/node
MacBook-Air-2010:Downloads mlim$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
MacBook-Air-2010:Downloads mlim$ node -v
v0.12.6
MacBook-Air-2010:Downloads mlim$ node

console.log('hello node');
hello node
undefined

(^C again to quit)

MacBook-Air-2010:Downloads mlim$

b) Now I run the "sudo npm install airsonos -g" command and got some errors:
 
MacBook-Air-2010:Downloads mlim$ sudo npm install airsonos -g
Password:

npm ERR! git clone --template=/Users/mlim/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /Users/mlim/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef: xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/mlim/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /Users/mlim/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef
npm ERR! xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mlim/Downloads/npm-debug.log

Note: At this point, it opened a window and it seems to be installing something.  Then when I tried to run the "airsonos" command, it errors out.

MacBook-Air-2010:Downloads mlim$ airsonos
-bash: airsonos: command not found

**Comment by va3lim** [comment]
Prior to running the above command "sudo nom install airsonos -g", I downloaded and installed node-v0.12.6.pkg.

**Comment by va3lim** [comment]
d) I ran "airsonos" command.

MacBook-Air-2010:Downloads mlim$ airsonos
Searching for Sonos devices on network...
Setting up AirSonos for Office {192.168.123.109:1400}

Note: I leave the Terminal session opened.

e) Opened System Preferences and go to Sound, set the Output to "Office (AirSonos)  AirPlay".

f) On iTunes, when I tried to set the airplay output to "Office (AirSonos)", I got an error message saying "The AirPlay device “Office (AirSonos)” is not compatible with this version of iTunes.".

**Comment by va3lim** [comment]
Did I do anything wrong? Please advise how to make AirSonos work on Yosemite and iTunes 12.2.  Thanks.

**Comment by va3lim** [comment]
Did I do anything wrong? Please advise how to make AirSonos work on OS X Yosemite 10.10.4 and iTunes 12.2.  Thanks.

**Comment by chadyj** [comment]
I had a similar problem running the latest version of node.  Downgrading node to v0.10.33 fixed the problem for me.

**Comment by spliket** [comment]
If you've selected the Airplay output in preferences, you shouldn't need to reselect it in iTunes. Did you try selecting the output in preferences and then just playing music out of iTunes?

**Comment by lappenlui** [comment]
same problem here. even when i try to select the output device in mac osx and not in tunes it gives out an error "could not connect with xxx" . if i try to put output in itunes it says error -15000 codec problems. guess its because of either mac osx or itunes update.

**Comment by va3lim** [comment]
This was what I did previously.

Opened System Preferences and go to Sound, set the Output to "Office (AirSonos) AirPlay".  When I go to iTunes and tried to play a song, there's no sound (because the sound output got switched to my Apple TV).  So I tried manually set it to airsonos in iTunes, then I got this error:

An error occurred while connecting to the AirPlay device “Office (AirSonos)”. An unknown error occurred (-15000).

I'll try chadyl's suggestion tomorrow night - downgrade node to v0.10.33. 

Thanks to those who replied.

**Comment by va3lim** [comment]
I've verified that airsonos is working after downgrading node to v0.10.33.  I can play my iTunes music and    movies using my Sonos speakers.  As many people have mentioned, there is lip sync issue when watching movies.  Thanks to chadyl for the tip.
