### ISSUE TITLE
Does airsonos work with Sonos update 5.4?

### ISSUE THREAD

**Issue by MartinAyla** [stephen/airsonos#189]
It looks like Sonos is starting to roll out the updated app in the App Store, so it would be nice to know if it's safe to update.

I saw another Github issue that mentioned that the 5.4 update breaks airsonos.

**Comment by DeLub** [comment]
For me airsonos stopt working after I updated my Sonos to 5.4. When I try to play a track in iTunes, I get an error message stating "cannot connect to Living Room (airsonos)". There's no further output available in the terminal I run airsonos in. Not sure what's going on...

**Comment by thoschl** [comment]
As mentioned here https://github.com/stephen/airsonos/issues/169
by dbdrwdn airsonos works with 5.4. It was a problem to play music directly from iTunes even before Sonos 5.4. My devices are working fine - even the grouped ones.

**Comment by DeLub** [comment]
I knew that. I'm not sure what was happening, but it seems that rebooting my sonos devices helped. So no further issues here.
