### ISSUE TITLE
Not publish Bonjour service AirSonos as Apple TV Device

### ISSUE THREAD

**Issue by loretoparisi** [stephen/airsonos#191]
macbookproloreto:airsonos admin$ node index.js 
Searching for Sonos devices on network...
Setting up AirSonos for PostazioneLoreto {192.168.2.150:1400}

I cannot see the bonjour service "airplay.tcp" in the airplay service list and the iPhone/iOS 8.4 cannot see in the Control Center menu. No luck with MacOS 10.11
I'm using node v0.10.24 / MacOS 10.11

**Comment by stephen** [comment]
AirSonos should be publishing `_raop._tcp`, not `airplay.tcp` (which I think is for the video protocol).

**Comment by stephen** [comment]
Going to track 10.11/iOS 9 here: https://github.com/stephen/airsonos/issues/191
