### ISSUE TITLE
Perfect configuration to install AirSonos?

### ISSUE THREAD

**Issue by vallieres** [stephen/airsonos#192]
Hello,

I would like to get AirSonos install on my Mac, but I have issues. There are many very specific prerequisites that should be respected. Notably the NodeJS version cannot be 0.12.x.

Does anybody have a defined list?

* Mac OS 10.10.4
* NodeJS, version?
* Latest Xcode and command line tools?
* Anything else?

I'm asking because I tried to get AirSonos to work a few times over the last few months with no success whatsoever. I regularly format my machines and even with a very clean MacOS I never got it right. I'm sure I'm missing a tiny stupid thing so I'm opening this issue to make some sens out of it.

Thanks!

**Comment by miho** [comment]
For the SonoAir app we still use node 0.10.28 which work fine for Mac OS X.

**Comment by vallieres** [comment]
> npm --version
1.4.9
> node --version
v0.10.28

With both of these I still can't install it, get a bunch of errors.

```
gyp ERR! node -v v0.10.28  
gyp ERR! node-gyp -v v0.13.0  
gyp ERR! not ok  
npm ERR! lame@1.2.2 install: node-gyp rebuild  
npm ERR! Exit status 1
```

**Comment by vallieres** [comment]
So I ended up uninstalling NodeJS and NPM completely per these instructions: http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

And then reinstall the exact same version as above as the only version on my system. It install and run, but does not show up on my iPhone. :(

**Comment by stephen** [comment]
0.12 is now supported. Please open a separate issue for other problems.
