### ISSUE TITLE
Problems installing on MAC OS X 10.10.4

### ISSUE THREAD

**Issue by aaranedac** [stephen/airsonos#199]
Please help. I got a lot of errors when trying to install airsonos:
ANDRESs-MacBook-Pro:package andresaraneda$ sudo npm install airsonos -g
Password:
 
> mdns@2.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/andresaraneda/.node-gyp/0.10.33'
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
 
> lame@1.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/andresaraneda/.node-gyp/0.10.33'
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm ERR! lame@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.2.2 install script.
npm ERR! This is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/andresaraneda/.npm/airsonos/0.1.1/package
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by stephen** [comment]
This is an issue with node-gyp, not airsonos directly: https://github.com/nodejs/node-gyp/issues/222
