### ISSUE TITLE
Airsonos on QNAP

### ISSUE THREAD

**Issue by lremmac** [stephen/airsonos#205]
I am trying to install this on a qnap NAS.  I have got fairly far but now I am not sure where to get the avahi lib packages from.  I have tried 

ipkg install avahi-compat-libdns_sd
or
ipkg install libavahi-compat-libdnssd-dev

Also get a ENOSPC  error when installing but not sure if this is just related to the missing packages above...

Any help gratefully received.

**Comment by stephen** [comment]
`ENOSPC` is an error for lack of space on disk to install. Try clearing up some space on your device? Otherwise, feel free to open an ew issue with a full error log.
