### ISSUE TITLE
An unknown error occurred (-15000).

### ISSUE THREAD

**Issue by jleow** [stephen/airsonos#206]
still unable to get airsonos to work on Mac OS X Yosemite 10.10.5 and iTunes 12.2.2.25
the error message i get is the same as above:

An error occurred while connecting to the AirPlay device “Great Room (AirSonos)”. An unknown error occurred (-15000).

i am only able to get it to stream through a mobile device (iPhone Music App) but not from my Mac laptop.

i have already set my systems preferences -> sound -> output --> airsonos 

and of course on iTunes on my mac (airsonos) -- single 

but this is still not working and streaming from my mac computer. 

any help much appreciated.

**Comment by jleow** [comment]
anyone?
or is there a way to uninstall everything and reinstall again to give it another go? 

thanks

**Comment by stephen** [comment]
You should only set the system audio output, not the one from iTunes.
