### ISSUE TITLE
Install problem on Yosemite

### ISSUE THREAD

**Issue by jmesberg** [stephen/airsonos#214]
Steven, I know you've stated in another response that the problems with mdns install are not within your domain to fix (and fully understand!), just wondering if you, or any other airsonos user, is aware of how to address this. No matter what I try I continue to get: "Failed at the mdns@2.2.2 install script 'node-gyp rebuild" error. I've tried whatever I could find online including:
- ensuring no spaces in usr directory
- ensuring that I had Xcode command line tools installed
- ensuring I didn't have python 3 installed

Does anyone here have any other suggestions?

**Comment by augustj** [comment]
I saw something similar when I was using node.js.org's OSX installer that said it was version 4.0.0.  When I switched to installing node 0.10.36 via homebrew, I had no problems.

**Comment by chasylexus** [comment]
I've tried to install airsonos via npm installed with node via homebrew but I've got an error:
```
  SOLINK_MODULE(target) Release/bindings.node
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! path /usr/local/lib/node_modules/airsonos/bin/index.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/airsonos/bin/index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/home/npm-debug.log
```

**Comment by augustj** [comment]
@chasylexus Looks like you're using node 0.12.7  Does the install still fail if you switch to a 0.10.X version of node? (I used 0.10.36).

**Comment by jmesberg** [comment]
Thank you for suggestion. I'll try that. Anything special I should know regarding uninstalling 0.12.7 version of Node before I install older one?

**Comment by chasylexus** [comment]
@augustj Thank you. I've reinstalled node 0.12.7 and it's OK.

**Comment by chasylexus** [comment]
Does anybody knows:
If I use Sonos Bridge and airsonos will the Sonos Bridge used when I will airplay music from my Mac of iOS devices to Sonos players?
