### ISSUE TITLE
Install Problem on Mint 17.2

### ISSUE THREAD

**Issue by nukewales** [stephen/airsonos#218]
Hey, great and useful Software. Always worked fine on my ubuntus. But on Mint i cant get it to work, here is the result of "sudo npm install airsonos -g"
(i pre-created "/home/server/.node-gyp/4.0.0", but no change)

npm WARN cannot run in wd airsonos@0.2.2 babel ./lib/ -d ./bin/ (wd=/home/server/airsonos)
npm WARN engine nodetunes@0.2.0: wanted: {"node":"0.12.x"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN optional dep failed, continuing fsevents@0.3.8
 
> mdns@2.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/server/.node-gyp/4.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp"
make: Verzeichnis »/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/build« wird betreten
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_sd.cpp:1:
../node_modules/nan/nan.h:120:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:115:25: error: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Signature> NanNew(v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../node_modules/nan/nan.h:207:78: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
     return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                              ^
../node_modules/nan/nan.h:207:78: note: candidate is:
In file included from /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/node.h:42:0,
                 from ../src/mdns.hpp:11,
                 from ../src/dns_sd.cpp:1:
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/v8.h:4675:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_sd.cpp:1:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:289:3: error: redefinition of ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’
   NanNew<v8::StringObject, v8::Handle<v8::String> >(
   ^
../node_modules/nan/nan.h:282:3: error: ‘v8::Local<T> NanNew(P) [with T = v8::StringObject; P = v8::Local<v8::String>]’ previously declared here
   NanNew<v8::StringObject, v8::Local<v8::String> >(
   ^
../node_modules/nan/nan.h:307:36: error: redefinition of ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:301:36: error: ‘template<class T> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:319:36: error: redefinition of ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Local<v8::String>, v8::RegExp::Flags)’
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:313:36: error: ‘template<class T, class P> v8::Local<v8::RegExp> NanNew(v8::Handle<v8::String>, v8::RegExp::Flags)’ previously declared here
   NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                    ^
../node_modules/nan/nan.h:778:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:778:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:782:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:782:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:789:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:789:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:24:0,
                 from ../src/mdns.hpp:12,
                 from ../src/dns_sd.cpp:1:
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/mdns.hpp:12:0,
                 from ../src/dns_sd.cpp:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:793:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:800:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Fehler 1
make: Verzeichnis »/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/build« wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
\
> lame@1.2.3 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/server/.node-gyp/4.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/.node-gyp"
make: Verzeichnis »/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/build« wird betreten
deps/mpg123/test.target.mk:123: Warnung: Die Befehle für das Ziel »Release/test« werden überschrieben
deps/lame/test.target.mk:131: Warnung: Alte Befehle für das Ziel »Release/test« werden ignoriert
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c: In function ‘do_gain_analysis’:
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable ‘rov’ [-Wunused-variable]
     RpgResult_t *const rov = &gfc->ov_rpg;
                        ^
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable ‘rsv’ [-Wunused-variable]
     RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                                ^
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable ‘cfg’ [-Wunused-variable]
     SessionConfig_t const *const cfg = &gfc->cfg;
                                  ^
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
../deps/lame/libmp3lame/quantize.c: In function ‘VBR_new_iteration_loop’:
../deps/lame/libmp3lame/quantize.c:1734:28: warning: variable ‘fullframebits’ set but not used [-Wunused-but-set-variable]
         int     mean_bits, fullframebits;
                            ^
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  AR(target) Release/obj.target/deps/lame/libmp3lame.a
  COPY Release/libmp3lame.a
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/compat.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/parse.o
../deps/mpg123/src/libmpg123/parse.c: In function ‘check_lame_tag’:
../deps/mpg123/src/libmpg123/parse.c:184:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(fr->track_frames > TRACK_MAX_FRAMES) fr->track_frames = 0; /* endless stream? */
                           ^
../deps/mpg123/src/libmpg123/parse.c: In function ‘handle_id3v2’:
../deps/mpg123/src/libmpg123/parse.c:1013:31: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  else debug("no useful ID3v2");
                               ^
../deps/mpg123/src/libmpg123/parse.c: In function ‘skip_junk’:
../deps/mpg123/src/libmpg123/parse.c:1081:71: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  else debug1("hopefully found one at %"OFF_P, (off_p)fr->rd->tell(fr));
                                                                       ^
../deps/mpg123/src/libmpg123/parse.c: In function ‘wetwork’:
../deps/mpg123/src/libmpg123/parse.c:1149:114: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
    if(VERBOSE3) debug3("resync try %li at %"OFF_P", got newhead 0x%08lx", try, (off_p)fr->rd->tell(fr),  newhead);
                                                                                                                  ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/frame.o
../deps/mpg123/src/libmpg123/frame.c: In function ‘INT123_frame_buffers’:
../deps/mpg123/src/libmpg123/frame.c:285:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(2*2*0x110*sizeof(real) > buffssize)
                            ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/format.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/equalizer.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/id3.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/optimize.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/readers.o
../deps/mpg123/src/libmpg123/readers.c: In function ‘plain_read’:
../deps/mpg123/src/libmpg123/readers.c:60:70: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(VERBOSE3) debug2("read %li bytes of %li", (long)ret, (long)count);
                                                                      ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘bc_add’:
../deps/mpg123/src/libmpg123/readers.c:630:93: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(size >=4) debug4("first bytes: %02x %02x %02x %02x", data[0], data[1], data[2], data[3]);
                                                                                             ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘bc_forget’:
../deps/mpg123/src/libmpg123/readers.c:728:42: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  else debug("forget with nothing there!");
                                          ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘INT123_feed_more’:
../deps/mpg123/src/libmpg123/readers.c:763:33: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(VERBOSE3) debug("feed_more");
                                 ^
../deps/mpg123/src/libmpg123/readers.c:772:82: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
   (unsigned long)fr->rdat.buffer.last->size, (unsigned long)fr->rdat.buffer.size);
                                                                                  ^
../deps/mpg123/src/libmpg123/readers.c: In function ‘buffered_fullread’:
../deps/mpg123/src/libmpg123/readers.c:848:97: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
    if(VERBOSE3) debug1("buffered_fullread: buffering %li bytes from stream (if > 0)", (long)got);
                                                                                                 ^
../deps/mpg123/src/libmpg123/readers.c:856:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if(got < sizeof(readbuf)) /* That naturally catches got == 0, too. */
           ^
../deps/mpg123/src/libmpg123/readers.c:867:73: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  if(VERBOSE3) debug2("wanted %li, got %li", (long)count, (long)gotcount);
                                                                         ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/tabinit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/libmpg123.o
../deps/mpg123/src/libmpg123/libmpg123.c: In function ‘mpg123_plain_strerror’:
../deps/mpg123/src/libmpg123/libmpg123.c:1581:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(errcode >= 0 && errcode < sizeof(mpg123_error)/sizeof(char*))
                             ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/index.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/stringbuf.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy2utf8.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/ntom.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_8bit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer1.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer2.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer3.o
../deps/mpg123/src/libmpg123/layer3.c: In function ‘III_dequantize_sample’:
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:804:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:818:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:842:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:890:4: note: in expansion of macro ‘REFRESH_MASK’
    REFRESH_MASK;
    ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1021:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1036:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1059:6: note: in expansion of macro ‘REFRESH_MASK’
      REFRESH_MASK;
      ^
../deps/mpg123/src/libmpg123/layer3.c:695:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while(num < BITSHIFT) { \
            ^
../deps/mpg123/src/libmpg123/layer3.c:1088:4: note: in expansion of macro ‘REFRESH_MASK’
    REFRESH_MASK;
    ^
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_real.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_float.o
  AR(target) Release/obj.target/deps/mpg123/libmpg123.a
  COPY Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
../deps/lame/libmp3lame/vector/xmm_quantize_sub.c: In function ‘fht_SSE2’:
../deps/lame/libmp3lame/vector/xmm_quantize_sub.c:172:20: warning: variable ‘v_s2’ set but not used [-Wunused-but-set-variable]
             __m128 v_s2;
                    ^
  AR(target) Release/obj.target/deps/lame/liblamevectorroutines.a
  COPY Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
  CXX(target) Release/obj.target/bindings/src/node_lame.o
  CXX(target) Release/obj.target/bindings/src/node_mpg123.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Verzeichnis »/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/build« wird verlassen
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/server/npm-debug.log

**Comment by stephen** [comment]
I think node 4.0.0 support isn't quite there. You can use node 0.12.7 via a tool like [n](https://www.npmjs.com/package/n) in the meantime.
