### ISSUE TITLE
Cant find the Sonos players on iOS 9

### ISSUE THREAD

**Issue by townsmcp** [stephen/airsonos#219]
I have AirSonos running on a Windows 7 machine (I have actually turned it to a Service using NSSM so the command prompt isnt open all the time and it then auto loads on reboot etc). Everything worked fine on iOS 8 (and still does on my iPad Air with iOS 8.4) however I cant see the discovered Sonos players on iOS 9. Rebooting phone etc still doesnt show it as an option

**Comment by czekaj** [comment]
Duplicates https://github.com/stephen/airsonos/issues/177
