### ISSUE TITLE
El Capitan Breaks Airsonos

### ISSUE THREAD

**Issue by turbojones** [stephen/airsonos#227]
Looks like the new OS is creating issues with my beloved Airsonos. The device no longer shows as an output device after the upgrade.

Anyone else seeing this?

**Comment by gareaugorille** [comment]
Same here. Airsonos worked fine with Mountain Lion, but since I have upgraded to El Capitan, my Sonos devices do not show up as output. Has anybody managed to make Airsonos work with El Capitan?

**Comment by GodsLonelyMan** [comment]
Same here. You can still run AirSonos on El Capitan and it will still expose the Sonos devices on airplay.

However to actually broadcast sound to the Sonos speaker(s) you will need a < iOS 9/OSX 10.11 device.

**Comment by davidmatas** [comment]
Duplicate #177
