### ISSUE TITLE
Tunnels set up but no new speakers listed

### ISSUE THREAD

**Issue by rmwiseman** [stephen/airsonos#240]
I run airsonos (either as a normal user or as root) and it appears to have succeeded -- it says "Search complete. Set up 2 device tunnels." at least -- but when I go to Sound --> Output in System Preferences, only "Internal Speakers" is listed.

I'm using node v5.1.0 and airsonos v0.2.5 on OS X 10.7.5.

Any ideas what I'm doing wrong?  I believe I've followed all the instructions!

Thanks.

**Comment by auchenberg** [comment]
I had the same issue. Solved by upgrading nodetunes.

https://github.com/stephen/airsonos/pull/241

**Comment by rmwiseman** [comment]
Thanks, but I literally installed the latest version of airsonos (which I assume contains the latest nodetunes) and tried it.  I also tried SonoAir (latest version) and that behaves in the same way: claims it has connected but no speakers appear.

**Comment by auchenberg** [comment]
The current master doesn't use the latest version of nodetunes, and that's
why it doesn't work. Ser the pull request.

**Comment by rmwiseman** [comment]
Ah, OK, thanks.  So will a simple `npm install nodetunes` do the trick?

**Comment by auchenberg** [comment]
You need to pull my branch from the pull request that upgrade `nodetunes`. See https://github.com/stephen/airsonos/pull/241

Or simple update `package.json` with:
```
"nodetunes": "0.3.0"
```

followed by running `npm install`

**Comment by rmwiseman** [comment]
I don't understand much about git, to be honest, so I don't know what pulling is compared to cloning.  But here's what I tried:
```sh
git clone https://github.com/auchenberg/airsonos.git
cd airsonos
vi package.json # changing the version of nodetunes to 0.3.0
npm install
node ./bin/index.js
```
Apologies if that's not what you're suggesting I do.  It wasn't successful anyway: it built OK but no change in the final result.
