### ISSUE TITLE
OSX 10.9.2 install problem

### ISSUE THREAD

**Issue by shenzo1** [stephen/airsonos#25]
Hi Stephen,

Thanks for this great piece of coding! I have troubles installing it on macosx 10.9.2. Here's the log. Can you help me out? Thanks.

air:airsonos-master shenzo$ git clone https://github.com/stephen/airsonos.git
Cloning into 'airsonos'...
remote: Reusing existing pack: 236, done.
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 242 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (242/242), 704.31 KiB | 116.00 KiB/s, done.
Resolving deltas: 100% (117/117), done.
Checking connectivity... done.
air:airsonos-master shenzo$ cd airsonos
air:airsonos shenzo$ npm install -g
npm ERR! error rolling back Error: EACCES, unlink '/usr/lib/node_modules/airsonos'
npm ERR! error rolling back  airsonos@0.0.16 { [Error: EACCES, unlink '/usr/lib/node_modules/airsonos']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/lib/node_modules/airsonos' }
npm ERR! Error: EACCES, unlink '/usr/lib/node_modules/airsonos'
npm ERR!  { [Error: EACCES, unlink '/usr/lib/node_modules/airsonos']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/lib/node_modules/airsonos' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/lib/node_modules/airsonos'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/shenzo/Downloads/airsonos-master/airsonos/npm-debug.log
npm ERR! not ok code 0
air:airsonos shenzo$ sudo npm install -g
Password:

> ursa@0.8.0 install /usr/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/ursa
> node-gyp configure build && node install.js

sh: node-gyp: command not found
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns2/build/Release/obj.target/dns_sd_bindings/src/dns_service_ref.o'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns2/build/Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns2/build/Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/tests/test-defaults.js'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/tests/test-defaults.js
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/tests/test-defaults.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/debug/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/debug/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/debug/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/mkdirp/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/mkdirp/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/mkdirp/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/fresh/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/fresh/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/fresh/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/merge-descriptors/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/merge-descriptors/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/merge-descriptors/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/buffer-crc32/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/buffer-crc32/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/buffer-crc32/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/send/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/send/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/send/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chown '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/range-parser/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/range-parser/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/range-parser/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/connect/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/connect/package.json
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/connect/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules'
npm ERR! error rolling back  airsonos@0.0.16 { [Error: ENOTEMPTY, rmdir '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules' }
npm ERR! ursa@0.8.0 install: `node-gyp configure build && node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the ursa@0.8.0 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build && node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/commander/History.md'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/commander/History.md
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/express/node_modules/commander/History.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/icecast-stack/test/dumps/4EverFloyd-1.dump'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/icecast-stack/test/dumps/4EverFloyd-1.dump
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/icecast-stack/test/dumps/4EverFloyd-1.dump
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/deps/lame/ChangeLog'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/deps/lame/ChangeLog
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/deps/lame/ChangeLog
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/airsonos/node_modules/lame/deps/lame/ChangeLog'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/shenzo/Downloads/airsonos-master/airsonos
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! path /usr/lib/node_modules/airsonos/node_modules/lame/deps/lame/ChangeLog
npm ERR! fstream_path /usr/lib/node_modules/airsonos/node_modules/lame/deps/lame/ChangeLog
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/shenzo/Downloads/airsonos-master/airsonos/npm-debug.log
npm ERR! not ok code 0

**Comment by johnbasile** [comment]
Hey Stephen. Been struggling to get AirSonos up over here. Not sure if it's an issue with NPM, the install, or ID-10T problem. Would greatly appreciate a pointer if there's anything sticking out to you. Thanks very much.
[2017-10-19T03_42_45_487Z-debug.log](https://github.com/stephen/airsonos/files/1397046/2017-10-19T03_42_45_487Z-debug.log)
