### ISSUE TITLE
OS X total uninstall

### ISSUE THREAD

**Issue by chasylexus** [stephen/airsonos#250]
Hi!
My airsonos installation broken. I've tried to reinstall it many times but not successful. Now I want to uninstall airsonos totally and after that install.
How to uninstall it totally?

**Comment by tobiastornros** [comment]
@chasylexus 
Run `npm uninstall airsonos` or `npm rm airsonos`. Add -g if the module is installed globally. 

Run `npm root -g` in your terminal to find where your global npm packages are installed and see if you can find the airsonos folder there.
