### ISSUE TITLE
airsonos won't install

### ISSUE THREAD

**Issue by mac03579** [stephen/airsonos#261]
Hi,
I installed node-v0.10.33 as a first step to getting your airsonos application working. When I put in the sudo command: sudo npm install airsonos -g, here's what happened:

sudo npm install airsonos -g
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/stephen/node-sonos.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/stephen/node-sonos.git) undefined
npm ERR! git clone git://github.com/stephen/node-sonos.git undefined
npm ERR! git clone git://github.com/stephen/node-sonos.git undefined
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/Jessica
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ENOGIT
npm ERR! not ok code 0

Not sure where it's going wrong...

**Comment by mccarvell** [comment]
Looks like you need to install git:
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
