### ISSUE TITLE
Can't find Sonos Devies on network

### ISSUE THREAD

**Issue by m-holmbom** [stephen/airsonos#30]
I've installed airsonos to my mac mini (Late 2012, OS X 10.9.4) but when I run airsonos, I get stuck at "Searching for Sonos Devices..." and then nothing happens. This has been tested at the longest for about 24 hours, still nothing happens. Same result when trying to run diagnostics, since no devices are found, nothing happens. My Sonos setup consists of a Bridge and a Play:1. Both are running version 5.0.

**Comment by YellowLemon1** [comment]
I can confirm this problem also exists on airsonos 0.2.2 running on the latest model Raspberry Pi 2: Was stuck on "Searching for Sonos Devices...". Solution was to unplug the Bridge. The Bridge must be blocking the multicast messages for device discovery. Nowadays Sonos has deprecated the Bridge so I will just throw it out.

Note: Changing the broadcast address in sonos.js like in these solutions did not help:
https://github.com/stephen/airsonos/issues/135
https://github.com/bencevans/node-sonos/issues/73
