### ISSUE TITLE
Raspberry PI 3

### ISSUE THREAD

**Issue by PatrickFist** [stephen/airsonos#309]
Hi everybody,

I followed all the simple and good instructions. But I can not install it on my new Raspberry Pi 3.

I get the output below:

`root@HAMMLWAPP8202:~# npm install airsonos -g --unsafe-perm

 airsonos@0.2.6 prepublish /root/airsonos
 babel ./lib/ -d ./bin/

lib/airsonos.js -> bin/airsonos.js
lib/diagnostics.js -> bin/diagnostics.js
lib/index.js -> bin/index.js
lib/tunnel.js -> bin/tunnel.js
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /root/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /root/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef: fatal: read error: Connection timed out
npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "airsonos" "-g" "--unsafe-perm"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /root/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef'...
npm ERR! fatal: read error: Connection timed out
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
root@HAMMLWAPP8202:~#`

Any ideas what the root cause could be? What should I try next?

Appreciate your feedback

**Comment by kozmic** [comment]
Looks like you have an connection issue to github.com. This is in your log:
```npm ERR! fatal: read error: Connection timed out```
Check that you can access the internet and try installing it again.
