### ISSUE TITLE
Airplay duplicating devices

### ISSUE THREAD

**Issue by smoob32** [stephen/airsonos#31]
Hi Stephen,

I have run airsonos for a few months and it works great with my iphone for streaming from youtube, however when i try to run the airplay through system volume on mac it duplicates the devices (i have 2 play:1's but it shows 4) and none of them will connect through airplay. Do you have any ideas what may cause this?

I have a bridge 2 x Play 1's and airsonos is running on OSX

Many thanks

Olly

**Comment by Mange** [comment]
I have this problem too, but when I run with `--diagnostics` they only show up once.

A summary of the data:
```
› airsonos --diagnostics | grep "^Device"
Device 	{"host":"192.168.33.180","port":1400,"state":{}} (ZPS5)
Device 	{"host":"192.168.33.134","port":1400,"state":{}} (ZPS5)
Device 	{"host":"192.168.33.172","port":1400,"state":{}} (ZP120)
Device 	{"host":"192.168.33.59","port":1400,"state":{}} (ZPS5)
Device 	{"host":"192.168.33.178","port":1400,"state":{}} (ZPS5)
Device 	{"host":"192.168.33.53","port":1400,"state":{}} (ZPS5)
Device 	{"host":"192.168.33.149","port":1400,"state":{}} (ZP90)
Device 	{"host":"192.168.33.160","port":1400,"state":{}} (ZPS5)
```

What should I do to help debug this issue?

![airplay](https://cloud.githubusercontent.com/assets/1599/6521829/c48768c4-c3dc-11e4-876a-dea688e6aa0e.png)

**Comment by Mange** [comment]
Seems like this could be the problem. In [`diagnostics.js`:12 you are using `sonos.search`](https://github.com/stephen/airsonos/blob/b00edc581329e5cdf1a4e2d6887b7e4b51eeba3f/lib/diagnostics.js#L12):

```js
sonos.search(function(device, model) {
```

But in [`main.js`:29-30 you are calling `sonos.LogicalDevices`](https://github.com/stephen/airsonos/blob/b00edc581329e5cdf1a4e2d6887b7e4b51eeba3f/lib/main.js#L29..L30):

```js
  sonos.LogicalDevice.search(function(err, devices) {
    devices.forEach(function(device) {
```
