### ISSUE TITLE
Support for node 0.11.x

### ISSUE THREAD

**Issue by philiptevans** [stephen/airsonos#33]
Hi,  I have installed Airsonos on my iMac and it searches and finds my Sonos devices.  However when I connect and try to play, the applications quits with the following error:-

Searching for Sonos devices on network...
Setting up AirSonos for Living Room3 {10.0.1.13:1400}
Setting up AirSonos for Living Room3 {10.0.1.47:1400}
Setting up AirSonos for Kitchen {10.0.1.46:1400}
Setting up AirSonos for Living Room3 {10.0.1.48:1400}
Segmentation fault: 11

**Comment by stephen** [comment]
Progress: As of `0.0.26`, airsonos builds on node >= 0.11.13.

However, there's a problem when attempting to connect to any device - it seems that none of the apple challenges are being accepted... The encryption doesn't seem to have changed (i.e. same outputs from `generateAppleResponse` from 0.10.x and 0.11.x), so perhaps the client device is perceiving the IP or mac address differently and rejecting the response? (Change in mdns module maybe?)

**Comment by stephen** [comment]
Closing in favor of https://github.com/stephen/airsonos/issues/113
