### ISSUE TITLE
AirSonos not discovered on iOS devices

### ISSUE THREAD

**Issue by shadi1989** [stephen/airsonos#363]
I've installed AirSonos on a Raspberry Pi but it can't be discovered from my iOS Devices(iPhone 7, iPad Air) but it can be discovered on my MacBook.

On my MacBook, i can connect to it but only can change the Volume, sound isn't send to my Sonos devices (1group, Playbar+SUB+2xPlay1)

Does anyone has an idea how to solve these issues?

**Comment by muricawashere** [comment]
+1, having same problem'o

**Comment by shadi1989** [comment]
Problem found.
default Airplay device(like AppleTV) = Video + Audio
You can still select it within the Youtube app and other apps.
