### ISSUE TITLE
Experiencing constant disconnects during audio stream on Raspberry Pi

### ISSUE THREAD

**Issue by dgrizzanti** [stephen/airsonos#42]
Experiencing constant disconnects on all my Sonos speakers when using AirSonos.  I've experienced this issue on Soundbard, Play:1, and Play:3 while attempting to AirPlay from an iPhone, iPad, and a Macbook (iPhone is running 8.0.2 and iPad is also running 8.0.2). OS x is 10.9.3.

Tried across a few different apps on my phone and streaming audio (not through iTunes on my Mac).

The audio from the source (iPhone, iPad, Mac) never stops playing but on the Sonos controller I see it disconnect and then say Connecting, Starting each time that the audio stops (it usually takes ~2-3 seconds before the controller reflects that he audio has stopped).

My wifi is not flaky otherwise and I am using a bridge with the Sonos speakers.

Only errors I see are on startup are
   **\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
   **\* WARNING **\* Please fix your application to use the native API of Avahi!
   **\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
   **\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
   **\* WARNING **\* Please fix your application to use the native API of Avahi!
   **\* WARNING **\* For more information see <http://0pointer.de/avahi-compat s=libdns_sd&e=node&f=DNSServiceRegister>
   Searching for Sonos devices on network...
   Setting up AirSonos for Bedroom {192.168.1.6:1400}
   Setting up AirSonos for Dining Room {192.168.1.7:1400}
   Setting up AirSonos for Living Room {192.168.1.5:1400}

**Comment by loretoparisi** [comment]
@dgrizzanti Hey David, how did you manage to overclock the pi? thanks!

**Comment by dgrizzanti** [comment]
@loretoparisi It may depend on what type of pi you have, but this should give you the info you need - https://www.howtogeek.com/269202/how-and-why-to-overclock-your-raspberry-pi-microcomputer/
