### ISSUE TITLE
Installation failure on OS X 10.10 (Yosemite)

### ISSUE THREAD

**Issue by hosemigeru** [stephen/airsonos#52]
I'm encountering an error installing on OS X 10.10 (Yosemite).  There is a build error when trying to build lame.  An extract of the log follows:

  LIBTOOL-STATIC Release/libmp3lame.a
libtool: unrecognized option `-static'
libtool: Try`libtool --help' for more information.
make: **\* [Release/libmp3lame.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

**Comment by timkelty** [comment]
I had the same issue because I had MAMP's binaries in my path. Thanks @hosemigeru!
