### ISSUE TITLE
Problem during installation of Airsonos on Mac OS 10.10

### ISSUE THREAD

**Issue by JBXIII** [stephen/airsonos#70]
Good day,
I'm trying to install Sonos and have the following issue during installation. I have to say that I'm not used to use the terminal, except to type exactly what is indicated into the forum. But here I don't understand the error messages:
```
MBPXXX:~ XXX$ sudo npm install airsonos -g
Password:
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
 
> mdns@2.2.0 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/XXX/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: Connection closed while downloading tarball file
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:239:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1098:46)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (http.js:1519:11)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:943:16
gyp ERR! stack     at process._tickCallback (node.js:419:13)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

> lame@1.1.1 install /usr/local/lib/node_modules/airsonos/node_modules/lame
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/XXX/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/airsonos/node_modules/lame/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: Connection closed while downloading tarball file
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:239:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1098:46)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (http.js:1519:11)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:943:16
gyp ERR! stack     at process._tickCallback (node.js:419:13)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/lame
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

> lame@1.0.3 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/XXX/.node-gyp/0.10.33"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: Connection closed while downloading tarball file
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:239:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1098:46)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (http.js:1519:11)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:943:16
gyp ERR! stack     at process._tickCallback (node.js:419:13)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! mdns@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.0 install script.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/XXX
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
MBPXXX:~ XXX$ 
```
Thanks in advance for your help.

**Comment by onomiko** [comment]
Hello. I've done all the above (npm cache clean; sudo npm install -g --unsafe-perm airsonos; installed XCode with Developer Extras; sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer), read TooTallNate's threads and still am not seeing the installation of AirSonos completing inside Terminal. I've been at it for hours having starting from scratch from the instructions on the AirSonos GIT page. Will someone weigh in? Here is the last set of errors I'm seeing after clearing up the same as posted by others above: http://pastebin.com/bpDXSSJA. I started fresh this morning after learning that AirSonos existed. Thank you.

**Comment by houndtt** [comment]
Hey guys,

I just wanted to write to share my experience with this if it can help. I'm using Mac OS X 10.10.1 and installed node-v0.10.35 from the vendor website. I first cloned the code with GitHub but then realised that this was not required. On my first attempt I realised I had permissions issues so then I tried using 'sudo'. When this was done it failed halfway and looked for some Apple Developer Tools which it asked for permission to install. Once this was done I tried for the last time and it went through with a number of warnings. It was however successful and I can run the 'airsonos' command and stream music from my iPad using my iMac.

The installation log which I just captured again is located here:   https://drive.google.com/file/d/0B5rb0xdORlKOQlBTTk9pMXAtbkE/view?usp=sharing

I hope that eventually the developer can make the deployment easier as well as eventually make this into a nice package which I can uninstall if required (since I really don't know how to do that at this point).

Regards,
Michael

**Comment by wbrooseboom** [comment]
Hello,

I would also like to use Airsonos but have no idea what you guys are talking about. Is there a way for a layman (who's used to select and drop a program into the applications folder) to install this? 

I just installed node and 'tried to' run the command "npm install airsonos -g". But that gave me all sorts of error messages. 

Is there some sort of step by step instruction manual. Ot could somebody please tell me what I should do. 

Thanks, 

Boudewijn

**Comment by wbrooseboom** [comment]
Reading the experiences of other I just tried the following

Last login: Wed Feb  4 11:22:10 on ttys000
Boudewijns-MacBook-Pro:~ boudewijnrooseboom$ sudo npm install -g --unsafe-perm airsonos
 
> mdns@2.2.2 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/dns_sd_bindings.node: Finished
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module

> lame@1.1.2 install /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

deps/mpg123/test.target.mk:147: warning: overriding commands for target `Release/test'
deps/lame/test.target.mk:155: warning: ignoring old commands for target `Release/test'
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/VbrTag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/bitstream.o
../deps/lame/libmp3lame/bitstream.c:992:24: warning: unused variable 'rov'
      [-Wunused-variable]
    RpgResult_t *const rov = &gfc->ov_rpg;
                       ^
../deps/lame/libmp3lame/bitstream.c:991:32: warning: unused variable 'rsv'
      [-Wunused-variable]
    RpgStateVar_t const *const rsv = &gfc->sv_rpg;
                               ^
../deps/lame/libmp3lame/bitstream.c:990:34: warning: unused variable 'cfg'
      [-Wunused-variable]
    SessionConfig_t const *const cfg = &gfc->cfg;
                                 ^
3 warnings generated.
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/encoder.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/fft.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/gain_analysis.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/id3tag.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/lame.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/newmdct.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/presets.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/psymodel.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/quantize_pvt.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/reservoir.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/set_get.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/tables.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/takehiro.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/util.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/vbrquantize.o
  CC(target) Release/obj.target/mp3lame/deps/lame/libmp3lame/version.o
  LIBTOOL-STATIC Release/libmp3lame.a
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/compat.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/parse.o
../deps/mpg123/src/libmpg123/parse.c:184:27: warning: comparison of integers of
      different signs: 'off_t' (aka 'long long') and 'unsigned long'
      [-Wsign-compare]
  ...if(fr->track_frames > TRACK_MAX_FRAMES) fr->track_frames = 0; /* endles...
        ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/frame.o
../deps/mpg123/src/libmpg123/frame.c:285:28: warning: comparison of integers of
      different signs: 'unsigned long' and 'int' [-Wsign-compare]
        if(2*2*0x110*sizeof(real) > buffssize)
           ~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/format.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/equalizer.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/id3.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/optimize.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/readers.o
../deps/mpg123/src/libmpg123/readers.c:856:11: warning: comparison of integers
      of different signs: 'ssize_t' (aka 'long') and 'unsigned long'
      [-Wsign-compare]
                        if(got < sizeof(readbuf)) /* That naturally catc...
                           ~~~ ^ ~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/tabinit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/libmpg123.o
../deps/mpg123/src/libmpg123/libmpg123.c:1581:29: warning: comparison of
      integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
        if(errcode >= 0 && errcode < sizeof(mpg123_error)/sizeof(char*))
                           ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/index.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/stringbuf.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/icy2utf8.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/ntom.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_8bit.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer1.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer2.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/layer3.o
../deps/mpg123/src/libmpg123/layer3.c:804:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:818:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:842:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:890:4: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                        REFRESH_MASK;
                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1021:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1036:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1059:6: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                        REFRESH_MASK;
                                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:1088:4: warning: comparison of integers of
      different signs: 'int' and 'unsigned long' [-Wsign-compare]
                        REFRESH_MASK;
                        ^~~~~~~~~~~~
../deps/mpg123/src/libmpg123/layer3.c:695:12: note: expanded from macro
      'REFRESH_MASK'
        while(num < BITSHIFT) { \
              ~~~ ^ ~~~~~~~~
8 warnings generated.
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/feature.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/dct64_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_real.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_float.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_stereo_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_s32.o
  CC(target) Release/obj.target/mpg123/deps/mpg123/src/libmpg123/synth_x86_64_float.o
  LIBTOOL-STATIC Release/libmpg123.a
  CC(target) Release/obj.target/lamevectorroutines/deps/lame/libmp3lame/vector/xmm_quantize_sub.o
  LIBTOOL-STATIC Release/liblamevectorroutines.a
  CXX(target) Release/obj.target/bindings/src/bindings.o
  CXX(target) Release/obj.target/bindings/src/node_lame.o
  CXX(target) Release/obj.target/bindings/src/node_mpg123.o
  SOLINK_MODULE(target) Release/bindings.node
  SOLINK_MODULE(target) Release/bindings.node: Finished
/usr/local/bin/airsonos -> /usr/local/lib/node_modules/airsonos/index.js
airsonos@0.0.26 /usr/local/lib/node_modules/airsonos
├── ip@0.3.2
├── flags@0.1.2
├── lodash@2.4.1
├── throttle@1.0.3 (stream-parser@0.3.0, readable-stream@1.0.33)
├── portastic@0.0.1 (async@0.1.22, coffee-script@1.3.3, commander@1.0.5)
├── sonos@0.6.1 (debug@0.7.4, underscore@1.5.2, xml2js@0.2.8, upnp-client@0.0.1, request@2.27.0)
├── nodetunes@0.1.2 (randomstring@1.0.3, random-mac@0.0.4, metricstream@0.0.0, priorityqueuejs@0.2.0, httplike@1.0.1, debug@2.1.1, node-forge@0.6.20, forge@2.3.0, mdns@2.2.2)
└── nicercast@0.0.8 (icecast-stack@0.3.0, express@3.5.3, lame@1.1.2)
$

**Comment by wbrooseboom** [comment]
I got it to work! Finally. 

I guess it would be helpful to create some step by step install manual as this code-stuff isn't doing it for the average mac user. 

Thanks anyway!

**Comment by tobaco** [comment]
@wbrooseboom 
what did you do, to get it to work?

**Comment by wbrooseboom** [comment]
Well, for those who are not familiar with terminal commands, herewith the layman's step by step instruction guide. The program Airsonos does not come with a clickable installation icon. Both installation and activation must be done by using commands in the terminal (it took me a few hours to get this).

1. Instal Node (http://nodejs.org)

2. Instal Xcode (https://developer.apple.com/xcode/downloads/)

3. Instal AirSonos in terminal with command:

- npm install airsonos -g

  or (most likely better):

- sudo npm install -g --unsafe-perm airsonos

4. Activate Airsonos in Terminal with command:

- airsonos


Best of luck. Hope this helps.

**Comment by skiddy1903** [comment]
just wanted to say thanks. just spent most of a day battling with the installation, mainly due to my lack of knowledge with node, git and pretty much everything this needs to run. And some incorrect and or missing components on my macbook. i worked through about 4 different errors before ending up with this one and discovering i didn't have but needed xcode installed.

so thanks for pointing me in that direction.

and thanks to stephen for a great package

**Comment by sportsnapper** [comment]
I've pretty much followed @wbrooseboom steps to get airsonos installed, and am continually getting the same error. Time's moved on , so I'm running OS X 10.10.3

>System Darwin 14.3.0
> command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "-g" "airsonos"
> cwd /Users/gareth
> node -v v0.10.36
> npm -v 1.4.28
> code ELIFECYCLE
> not ok code 0

The error appears to be in the lame 1.2.2 install 
>lame@1.2.2 install: `node-gyp rebuild`
> Exit status 1
> 
> Failed at the lame@1.2.2 install script.
> This is most likely a problem with the lame package,
> not with npm itself.
> Tell the author that this fails on your system:
>     node-gyp rebuild

I've noticed in the successful log above from @houndtt that lame was 1.2.1
Node is new to me -so it's all a bit frustrating when some users seem to install this without any problems, and other seemingly never succeed. I'd quite like this to run permanently on a Pi - but that may be even more daunting!

**Comment by sportsnapper** [comment]
Found the answer - for me at least. https://github.com/stephen/airsonos/issues/52 
>I had the same issue because I had MAMP's binaries in my path.

Now streaming over my Sonos from my Mac - :smile: 

I get all my speakers listed twice on airplay - but I've seen that as an issue here before.

Happy - now going to try to get this working on a Pi

**Comment by edwigemorin** [comment]
Hello,
I have pretty much the same issue, but I'm kind of a newbie using all these terminal commands and I cruely lack of knowledge with node, git, npm to be able to make airsonos work. Could you tell me how you did to solve that : 
> I had the same issue because I had MAMP's binaries in my path.
Thank you in advance.

**Comment by sportsnapper** [comment]
> export $PATH=/usr/local/bin:/usr/bin/:/bin:/sbin:/opt/X11/bin
Then sudo npm install etc. as above. Note that this does not change your path forever, but only until you restart terminal....

**Comment by edwigemorin** [comment]
Thank you for your answer.
It seems more complicated than I thought, after doing what you suggest I got another error:
> -bash: export: `/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Applications/MAMP/bin/php/php5.5.10/bin:/Applications/MAMP/Library/bin:/Applications/MAMP/bin/php/php5.4.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin=/usr/local/bin:/usr/bin/:/bin:/sbin:/opt/X11/bin': not a valid identifier

**Comment by sportsnapper** [comment]
Sorry, wrong command from my history - try 
>export PATH=/usr/local/bin:/usr/bin/:/bin:/sbin:/opt/X11/bin

**Comment by edwigemorin** [comment]
Yes ! Great :-) Thank you very much it works.
In fact it work perfectly with my iphone and the native music app as well as with for example the sound of a video payed with VLC or QuickTime
But it doesn't work with itunes on my macbook. I got this comment on the terminal: 
> Warning! Codec not supported (96 AppleLossless)
AirSonos currently does not support codecs used by applications such as iTunes or AirFoil.
Progress on this issue: https://github.com/stephen/nodetunes/issues/1
Warning! Codec not supported (96 AppleLossless)
AirSonos currently does not support codecs used by applications such as iTunes or AirFoil.
Progress on this issue: https://github.com/stephen/nodetunes/issues/1

I don't know if it's a normal behavior at the moment with airsonos or if it's due to the warning I got during the installation:
> npm WARN deprecated static-favicon@1.0.2: use serve-favicon module

**Comment by sportsnapper** [comment]
Good. I think that’s expected behaviour - I’ve used it with iTunes - but that’s with mp3’s rather than apple lossless



Gareth Jones


e: gareth@jonestheweb.com <x-msg://33/info@sports-alive.com> | t: 07870 667671 | w: www.sports-alive.com <x-msg://33/www.sports-alive.com> www.smart-pictures.co.uk

**Comment by edwigemorin** [comment]
Thank you Gareth.
Coming back on what I just said.
It DOES work with iTunes on macbook when you setup sound output in the pref pan of the macbook on the airsonos .
Thank you again for your help.
And thank you Stephen for Airsonos.
Have a nice day. Cheers.
Edwige

**Comment by muzie01** [comment]
I also followed the instructions above from @wbrooseboom but unfortunately am not having much luck. I'm pretty new at this coding thing so any help or advice would be greatly appreciated! I keep getting the error below:

XXXX-MacBook-Pro:~ XXXX$ sudo npm install airsonos -g
Password:
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1183:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:485:12)
npm WARN addRemoteGit  git://github.com/stephen/node-sonos.git#stephen-1.0.0 resetting remote /Users/andrewmuir/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: null,
npm WARN addRemoteGit   signal: 'SIGSEGV',
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/Users/XXXX/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /Users/XXXX/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef: 
npm ERR! Darwin 10.8.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1

npm ERR! Command failed: git clone --template=/Users/XXXX/.npm/_git-remotes/_templates --mirror git://github.com/stephen/node-sonos.git /Users/XXXX/.npm/_git-remotes/git-github-com-stephen-node-sonos-git-701294ef
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXXX/npm-debug.log
