### ISSUE TITLE
Latest Update Breaks Sonos Stereo Pairs

### ISSUE THREAD

**Issue by ambledown** [stephen/airsonos#76]
Hello! Thanks for the awesome software. 

After I updated to the latest version I found that my stereo pair of Play:3's are only playing from the left channel. I restarted all sources and computers and continued to have the problem. I then went into the Sonos controller, unpaired the Play:3's, and then repaired. The pair now works! However, when I switched the source the stereo pair seems to be broken again and only playing from the left channel again. I restarted Airsonos and the problem persisted. I am able to un-pair and then re-pair and it works again but not a great work around.

**Comment by stephen** [comment]
Support for paired and grouped speakers should be better in `0.1.1`.

**Comment by ambledown** [comment]
Working great! Thank you!

**Comment by stephen** [comment]
\o/
