### ISSUE TITLE
Airsonos and iPad1 iOS 5.1.1

### ISSUE THREAD

**Issue by jcplu** [stephen/airsonos#85]
When I start airsonos running on debian, my iPhone (iOS 7) works well with AirPlay,
but for my iPad1 (iOS 5.1.1) the sonos appears in the AirPlay list but it doesn't work (no sound).
An idea ???

**Comment by stephen** [comment]
Unfortunately, I don't have a device that old to test with.

Perhaps you can provide a `--verbose` dump?

**Comment by jcplu** [comment]
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Searching for Sonos devices on network...
Setting up AirSonos for Room1 {192.168.0.11:1400}
  nodetunes:server starting nodetunes server (Room1 (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +79ms
Setting up AirSonos for Room1 {192.168.0.45:1400}
  nodetunes:server starting nodetunes server (Room1 (AirSonos)) +24ms
  nodetunes:server broadcasting mdns advertisement (for port 5001) +64ms
Setting up AirSonos for Room2 {192.168.0.44:1400}
  nodetunes:server starting nodetunes server (Room2 (AirSonos)) +52ms
  nodetunes:server broadcasting mdns advertisement (for port 5002) +77ms
Setting up AirSonos for Room1 {192.168.0.42:1400}
  nodetunes:server starting nodetunes server (Room1 (AirSonos)) +98ms
  nodetunes:server broadcasting mdns advertisement (for port 5003) +145ms

Room1 = Playbar + Play1(L) +Play1(R)
Room2 = Play1

iPhone 4 (ios 7.x) : I have the Room1 (3 lines) and Room2 in the AirPlay list and it works with Room2 line and only with one line (out of 3) of the Room1.

iPad1 (ios 5.1.1) : I have the Room1 (3 lines) and Room2 in the AirPlay list but none works.
When selecting one of them, no sound and nothing more in the dump.
