### ISSUE TITLE
No connection to Airsonos with iPad iOS 8.1.1

### ISSUE THREAD

**Issue by krolli53** [stephen/airsonos#86]
Hi Stephen,

i get the following when I'm trying to connect with my iPad Air to the AirSonos on a Raspberry Pi.
The connect fails and music goes back to the iPad.

```
pi@raspberrypi ~ $ airsonos --verbose
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Searching for Sonos devices on network...
Setting up AirSonos for Küche {192.168.6.103:1400}
  nodetunes:server starting nodetunes server (Küche (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +205ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x1499e2bb7a09',
  'apple-challenge': 'vkrwSsL3SLu8EPttLyH7oQ==',
  'dacp-id': '586A41D339DDC830',
  'active-remote': '72061765',
  'user-agent': 'AirPlay/211.3' } +12s
  nodetunes:helper building challenge for vkrwSsL3SLu8EPttLyH7oQ== (ip: c0a80670, mac: 545200f7f230) +29ms
  nodetunes:helper computed challenge: zMzsEFaBsRiQYCEio2SBIKCg98gmibKMRooXEK8OI2zJ9y95JT5CmxKTA79WhvSB9IhiMfexeBcBMediSt3+gHQaemF660XL5igEdyce6OFqx/c983B7hFQjDkw+bHDmDyCZNuBlQXf2v4rcshyGRSNZnYzngAJlffJYiiKCGA6+JleRXq1alSVVAuWtOPv0GcTvsxgR2JSFMZINQwR9ob1mopaYwWhlbq0tj7+s54D/RzdHKDtTYeSnK1aZliBid1hGj/CA4J3n1bdVYFL/g57aXjjepjEovRUVwebwKCcCZIH+yqAo/vU81axBT620XPG/c74BR0z2auodRGw4xA== +8s
  nodetunes:rtsp received method ANNOUNCE (CSeq: 1)
{ 'x-apple-client-name': 'Florians iPad',
  cseq: '1',
  'x-apple-device-id': '0x1499e2bb7a09',
  'dacp-id': '586A41D339DDC830',
  'active-remote': '72061765',
  'content-type': 'application/sdp',
  'content-length': '601',
  'user-agent': 'AirPlay/211.3' } +90ms
  nodetunes:rtspmethods v=0
o=AirTunes 3236130421958461899 0 IN IP4 192.168.6.116
s=AirTunes
i=Florians iPad
c=IN IP4 192.168.6.116
t=0 0
m=audio 0 RTP/AVP 96
a=rtpmap:96 L16/44100/2
a=rsaaeskey:3meVlSntDC53zOZRM7pD8Pc+AvC45nTsqcV/3rRzXxmwToK5r6kHg6JlXOO4zzREFzQXr1SAwzZIW0yUccDyFoJFEKggloHV0E3pMqXCCMLAGHry6LiaFaiqbm4HsXJjy+LKuEUVDfF3TuNrII53t4yS53HS+p0tQQahNJNEIhCm7zzhVDmA6xGL+i2LA/r97NdUBdSHYg8V9LSNpB7yFrQtBqdBAJ2kJjh3tV11DInE2M6Ka1ag2Fl29MQdc9st1a5uasWbjNCgOz5Oc+Ddvk02CEPAyzakfU60mbRHftLa0e4SWvjTvG7U5X3cFzx+Ejs+xFP2gEX8ZycyvMCXCQ==
a=aesiv:A7Bivo08rgO7jrzn0I9dHA==
a=min-latency:11025
a=max-latency:88200
 +4ms
  nodetunes:rtspmethods client name reported (Florians iPad) +8s
  nodetunes:rtspmethods client considered connected +7ms
  nodetunes:rtsp client disconnected +267ms
^Cpi@raspberrypi ~ $ node --version
v0.10.34
pi@raspberrypi ~ $ 
```

**Comment by prefecti0nist** [comment]
Hi Stephen,

same for my setup here:
The playbar
- works from iMac via airsonos on iMac (10.10.1)
- doesn't work on iOS devices (8.1.1) via airsonos on iMac
- doesn't work on iOS devices (8.1.1) via airsonos on raspi (model b w/ upgraded wheezy)

//K

**Comment by stephen** [comment]
@prefecti0nist - are you also using a raspberry pi?

@krolli53 - it's possible your raspberry pi isn't powerful enough. Reports (and in my testing as well) are that you'll need to overclock to get decent performance/audio quality.

**Comment by krolli53** [comment]
@stephen my pi is overclocked to 1GHz and I changed the amount of reserved memory for GPU to the minimum because I did recognize that airsonos needs a lot of memory. It works with my MacBook Pro. Should I post another log with that?

And - I am sorry for my last post - I forgot to say, thank you for this great work and your support!

**Comment by prefecti0nist** [comment]
@stephen - yes. I had two instances of airsonos under test (not simultaneouls), one on the iMac and one on a raspberry pi (model b, no overclocking with ugraded packages before install).

Any IOS device was not able to stream to any of the instances (iMac or raspberry pi).
The only success was the iMac utilizing the airsonos instance on the iMac to stream to the playbar. I skipped the testing with the iMac utilizing the raspberry pi instance as the issued seemed to be located on iOS.

**Comment by erikbulow** [comment]
Hi, I can also confirm the problem. I can use the Airsonos with an overclocked raspberry pi B+ and a Ipad mini running ios 7, but as soon i try any other Iphone or ipad with ios 8.1.x it won't work. The ios 8 devices displays the sonos units as airplay devices but as soon i select one of them and try to stream  it hangs for a while and then goes back to local headphones or internal speaker.
