### ISSUE TITLE
Air Sonos compatible with Denon Heos

### ISSUE THREAD

**Issue by gurmukhp** [stephen/airsonos#87]
Hi there

I'm looking to purchase a Denon Heos and was wondering if you have any sonos specific code? If it's just a shoutcast radio, I think the Denon supports that also?

**Comment by stephen** [comment]
Hmm, I imagine it's possible, but out of the scope of airsonos. (i.e. not something I'd be interested in supporting within this package)

However, you're welcome to take apart (or fork airsonos), as you are correct - airsonos is more or less an airplay <-> shoutcast bridge. You can use the same [nodetunes](https://github.com/stephen/nodetunes) and [nicercast](https://github.com/stephen/nicercast) services and wire them together (neither have sonos-specific code). Can use (https://github.com/stephen/airsonos/blob/master/lib/main.js) as a guide for how this can be done, ignoring the Sonos-specific discovery code.
