### ISSUE TITLE
Support for Airplay Devices as Sonos Devices?

### ISSUE THREAD

**Issue by digitalmud** [stephen/airsonos#89]
Would it be possible for AirSonos to bridge Airplay and Sonos the other way and allow Sonos controllers to see and transmit to Airplay Devices?

**Comment by stephen** [comment]
Not with AirSonos. I imagine this is feasible, but none of the work required for that overlaps with AirSonos.

(also see: https://twitter.com/cryptochrome/status/518021893899968512)
