### ISSUE TITLE
No sound from any device in network on 10.10

### ISSUE THREAD

**Issue by MartinOST** [stephen/airsonos#93]
Hi,

Just installed the latest via 

sudo npm install -g airsonos and it installed without any problems. I can then select the Sonos speaker as my default output in my Mac. Yet, after doing so, I do not hear anything from the Sonos Play:1 speaker. Same goes for my iPhone. No sound :(

Any idea how to debug this?

Thanks!

**Comment by stephen** [comment]
Can you paste a verbose output (`airsonos --verbose`)?

**Comment by MartinOST** [comment]
Hi Stephen,

I did do the verbose output yesterday at home (I am at work right now). I will paste it when I get home.

Thanks!

**Comment by MartinOST** [comment]
Stephen, please find below the verbose output. I started AirSonos on my Mac Mini and tried to play a youtube video in Chrome (on the same machine)

MiniMe2:~ martin$ airsonos --verbose
Searching for Sonos devices on network...
Setting up AirSonos for Living Room {192.168.0.13:1400}
  nodetunes:server starting nodetunes server (Living Room (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +15ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
{ cseq: '0',
  'x-apple-device-id': '0x406c8f20acb1',
  'apple-challenge': 'sGUvmnDjyIV0dKW3zUm6bQ==',
  'user-agent': 'AirPlay/215.10' } +4s
  nodetunes:helper building challenge for sGUvmnDjyIV0dKW3zUm6bQ== (ip: c0a8000a, mac: 545200b9d019) +2ms
  nodetunes:helper computed challenge: WxGB8dSrjzZa+8BE0vF+coUsd3Lqm5Zo2tIMvNB+RW+C24XhUKu25R+8Nk72eicqsE790+E9iJEVZI3S1eOQvA1mMFGictM2L14bOKbQB1w3UAbhSctA2OOM40owh/mfjoUD+L1WquLMBoCPMSYu863VTZYwECW6imBGFsWxtmJXSaHSzX/Ywli3uav962LDXZgG+XF99zX2qXaViyX66xatqMMT4hCqTsWVWc4z/DZ0wAwQUOKnw+pprndqD9ajRvPXXevjd1P2T32rvaG3lrRdFwHsK6UIWvNqSuuknQTbDL3YHZv9+Adpavd6WNa5MDALADfLEwZGQ/tFCHf4kQ== +89ms
  nodetunes:rtsp received method OPTIONS (CSeq: 1)
{ cseq: '1',
  'x-apple-device-id': '0x406c8f20acb1',
  'apple-challenge': '1ET+N52gaAZ2UdQIC0F8BQ==',
  'dacp-id': 'CB52D162555C1C18',
  'active-remote': '2358935950',
  'user-agent': 'AirPlay/215.10' } +13ms
  nodetunes:helper building challenge for 1ET+N52gaAZ2UdQIC0F8BQ== (ip: c0a8000a, mac: 545200b9d019) +1ms
  nodetunes:helper computed challenge: un6n7vnFvtK8SffP44yyA4MnTCkAj+8tMXlc1xiqv3UWdvEdob3TDMVq1o77ldfz+IFvXKWh5XT/C850xtJmjGFUiSWH9pK7hR3+WkIaRdiCzjKgq/D6TJlPOXo1SmhcVIsvHT/0IZdrA5BdnFyhLgIO5vk/Ocl6CAEK9JHeV0qpO6kophdVMGL0ZgXkEzDe2bJVpPBBKUEMzX6e+14ON0juLFeMdIowgoTWPrjiXR6tZ0kT170BXYWzbQxdTQP9/9LKKVDBtCmq10vG0j6x/w5rrH6fB3D9ApxPMTka6i94TVrRIkhT/d55Yu/2X2LzHWHs9NoZB5NDML/7XMoWdw== +91ms
  nodetunes:rtsp received method OPTIONS (CSeq: 2)
{ cseq: '2',
  'x-apple-device-id': '0x406c8f20acb1',
  'apple-challenge': 'SIE/TdnSv9fdco2dxujb0A==',
  'dacp-id': 'CB52D162555C1C18',
  'active-remote': '1181353495',
  'user-agent': 'AirPlay/215.10' } +301ms
  nodetunes:helper building challenge for SIE/TdnSv9fdco2dxujb0A== (ip: c0a8000a, mac: 545200b9d019) +1ms
  nodetunes:helper computed challenge: S3MZTmqZSVFGRFFIuXpKJc2OJvL8ZqI7/2zJP8ggod4AtZQ2zkzX87UGxH0zDWCmhPkn+ChOYHy1SMHrfMvhhvGm1LxeXeQD/1iCBdEGyFRpfdrymOJ1kEX1wiYRSUyOL+xk3NegqgsQB90MlDdHWe2nj+M4eLzMcO0Zly48bw7wwQehs3fkez7rSaGhtp3REu4ClqA9Ja+m+y7SQd8d2rtV+97/xZPkMohJVHulzibGjoDXSM37Y1QzJrZrv7xlO+KU8ehgP2DqX1Cdm0ZFPoPU2vha5X9jOYLpwfo/7SjsDBVBAf734s4zrdnu/1paNuh2yDxPEbsMgtyB8uQphg== +72ms
  nodetunes:rtsp received method OPTIONS (CSeq: 3)
{ cseq: '3',
  'x-apple-device-id': '0x406c8f20acb1',
  'apple-challenge': 'XinDKMx1/v/djsXX3nLipQ==',
  'dacp-id': 'CB52D162555C1C18',
  'active-remote': '2928976984',
  'user-agent': 'AirPlay/215.10' } +11ms
  nodetunes:helper building challenge for XinDKMx1/v/djsXX3nLipQ== (ip: c0a8000a, mac: 545200b9d019) +1ms
  nodetunes:helper computed challenge: 1S0y7tHq7RDPNc2L2hXatXb782eED02nTG7CIU8Ry978vGtBdgih0NpBqR7Mwyrc626QjwcvbH9aH3I76az1Al4fXsUTvfBQmQ5HHJOXb56XBbFOJgtnLw5SdHRUe7lGuaQ59W7wOMZrQN8++I1S7gM1DPyNapWO1Si50l2e1LUOcHVl8IbXrTD5Gau881Z+I1AoiK8qh5VlQAHoK/OwGkL6vVqWTzAYmt/Nrl2FbhGuLb4QWMTJ4dwaomjuTEyTdtcVVeI5s6+LcREcPj/N4iKINOrMh90ygFoU0pfCbc4nRDC/bpTyqNTOSDWiMk9fnwNCxiyboGX8QsDZfzhEww== +72ms
  nodetunes:rtsp received method OPTIONS (CSeq: 4)
{ cseq: '4',
  'x-apple-device-id': '0x406c8f20acb1',
  'apple-challenge': 'SyJO1WLP0lhI+Hqfo/5TbA==',
  'dacp-id': 'CB52D162555C1C18',
  'active-remote': '2591775339',
  'user-agent': 'AirPlay/215.10' } +11ms
  nodetunes:helper building challenge for SyJO1WLP0lhI+Hqfo/5TbA== (ip: c0a8000a, mac: 545200b9d019) +0ms
  nodetunes:helper computed challenge: CMJQD0HAbRblGUPjb0gTJ8/xthii/GVMuo81tvtrv7Nov/BgL8x4NmwakHkQHokAF5O4uVDiU6z5Mf5QV56h/yzkiFQz6LyQqD0BFSp0G6rCDoCyQw8UYDCmIprhVO50BgAjszabYL3VxeBy1ERP9wP5suvhNGNLM70UYJDU6wBUxhHUeAwDBfPcaEv6MqLAwaDPlHjU87H3m+ez8jhvPiF+6/7vRwHK+WTa6FL2Zif9i8wPxdQRF5p6gxepfJOvmVFcWnlj0BB61mkGlZkEr2IrtQr9nLeoLUgICkG51ihcQTDs75dWWOlBfKOyYSnaZPyp5egqOmFQOpq3lO32ig== +73ms

**Comment by MartinOST** [comment]
Alas, Stephen!

I found the issue. I used to connect my Mac via WiFi to my home network. Yesterday, I also connected a LAN cable to my Mac. For some odd reason, AirSonos got confused big time. I switched the WiFi off, forcing it to use only one network interface. Et voila, it works like a charm.

Thanks!!

**Comment by stephen** [comment]
Hmm, I'm wondering what the difference was. @MartinOST - do you mind posting the start of the verbose output for when airsonos is working for you? Might be able to diff/see a discrepancy for why it did/didn't work.

**Comment by markcracknell** [comment]
@stephen / @MartinOST, 
I was having the same issue with no audio output - I have a mac set-up that uses both ethernet + wifi network connection.

I unplugged the ethernet cable, restarted airsonos and this fixed the issue - so it seems that having both connections active confuses audio output.

Let me know if you want the verbose output from working / not working.

**Comment by bkwu** [comment]
Hi @stephen, 

Thanks for you great program! I was trying to install it on my 32bit Win 7, but came out with following error. would you mind to advice how can I solve it?
------
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\bkw>where airsonos
C:\Users\bkw\AppData\Roaming\npm\airsonos
C:\Users\bkw\AppData\Roaming\npm\airsonos.cmd

C:\Users\bkw>airsonos
Unexpected result while probing for avahi: { [Error: dns service error: unknown
error code] errorCode: -65563 }
Searching for Sonos devices on network...
Setting up AirSonos for Living Room {192.168.1.123:1400}

Error: dns service error: unknown error code
    at new Advertisement (C:\Users\bkw\AppData\Roaming\npm\node_modules\airsonos
\node_modules\nodetunes\node_modules\mdns\lib\advertisement.js:56:10)
    at Object.create [as createAdvertisement] (C:\Users\bkw\AppData\Roaming\npm\
node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\advertisement
.js:64:10)
    at NodeTunes.<anonymous> (C:\Users\bkw\AppData\Roaming\npm\node_modules\airs
onos\node_modules\nodetunes\lib\server.js:65:21)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)
-------
Thanks in advance!

**Comment by stephen** [comment]
@bkwu see https://github.com/agnat/node_mdns/issues/104
