### ISSUE TITLE
Hangs during the search for SONOS devices

### ISSUE THREAD

**Issue by skihikeplay** [stephen/airsonos#94]
First crack at this and all seemed to go well. Found both of my SONOS devices but just hangs after "seeing" them. Here's the code:

Last login: Fri Jan 23 07:21:59 on ttys000
stevesarmay2014:~ root# airsonos
Searching for Sonos devices on network...
Setting up AirSonos for Portable {192.168.1.142:1400}
Setting up AirSonos for Living Room {192.168.1.141:1400}

Any help would be appreciated. What is the next step, btw? If working right, would both of these just appear in my Airplay drop down list?

**Comment by stephen** [comment]
@skihikeplay - You should be able to see the airplay devices on your network after this (i.e. through os x system audio)  code runs
